import { registerCapability, type CapabilityInput } from "./index.js";

// ─── Financial year dates lookup — pure algorithmic ─────────────────────────
// Returns fiscal year dates and filing deadlines for 40+ countries.

interface FiscalYearInfo {
  country_code: string;
  country_name: string;
  financial_year_start: string; // MM-DD
  financial_year_end: string; // MM-DD
  fiscal_year_matches_calendar: boolean;
  tax_filing_deadline: string;
  vat_filing_frequency: string;
  annual_report_deadline: string;
  notes: string;
}

const FISCAL_YEAR_DATA: Record<string, FiscalYearInfo> = {
  SE: {
    country_code: "SE",
    country_name: "Sweden",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 1 (calendar year companies); 6 months after FY end for broken fiscal years",
    vat_filing_frequency: "Monthly (turnover >40M SEK), quarterly (1-40M SEK), or annually (<1M SEK)",
    annual_report_deadline: "7 months after financial year end",
    notes: "Companies may choose a broken fiscal year (e.g., May-Apr, Sep-Aug). Calendar year is most common. Bolagsverket filing required.",
  },
  NO: {
    country_code: "NO",
    country_name: "Norway",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "End of May (companies); April 30 (individuals)",
    vat_filing_frequency: "Bi-monthly (6 terms/year); annually for small businesses",
    annual_report_deadline: "June 30 (6 months after FY end)",
    notes: "Norwegian law generally requires calendar year. Annual accounts must be approved by AGM within 6 months of FY end.",
  },
  DK: {
    country_code: "DK",
    country_name: "Denmark",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "July 1 (6 months after income year end)",
    vat_filing_frequency: "Quarterly (default); monthly (turnover >50M DKK); semi-annually (<5M DKK)",
    annual_report_deadline: "5 months after FY end (ApS/A/S); 6 months (Class B)",
    notes: "Companies may choose non-calendar fiscal year. Tax year always follows fiscal year.",
  },
  FI: {
    country_code: "FI",
    country_name: "Finland",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "4 months after fiscal year end",
    vat_filing_frequency: "Monthly (default); quarterly (turnover <100K EUR); annually (<30K EUR)",
    annual_report_deadline: "4 months after FY end (filing to Trade Register within 2 months of AGM)",
    notes: "Companies may freely choose their fiscal year period. Calendar year is most common.",
  },
  DE: {
    country_code: "DE",
    country_name: "Germany",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "July 31 (without tax advisor); February 28/29 of second following year (with tax advisor)",
    vat_filing_frequency: "Monthly (VAT >7,500 EUR/year); quarterly (1,000-7,500 EUR); annually (<1,000 EUR)",
    annual_report_deadline: "12 months after FY end (small); 6 months (medium/large) — filed in Bundesanzeiger",
    notes: "AG/GmbH may choose non-calendar fiscal year. Trade tax (Gewerbesteuer) due alongside corporate income tax.",
  },
  GB: {
    country_code: "GB",
    country_name: "United Kingdom",
    financial_year_start: "04-06",
    financial_year_end: "04-05",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "9 months + 1 day after accounting period end (corporation tax); January 31 following tax year (individuals)",
    vat_filing_frequency: "Quarterly (aligned with VAT periods); monthly (optional)",
    annual_report_deadline: "9 months after FY end (private companies); 6 months (public companies) — filed at Companies House",
    notes: "Tax year: Apr 6 - Apr 5. Companies choose their own accounting reference date. Corporation tax payment due 9 months + 1 day after period end.",
  },
  US: {
    country_code: "US",
    country_name: "United States",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "April 15 (individuals/C-corps calendar year); March 15 (S-corps/partnerships); extension to October 15",
    vat_filing_frequency: "N/A (no federal VAT; state sales tax varies by state)",
    annual_report_deadline: "Varies by state; typically annually with Secretary of State",
    notes: "Companies may elect any fiscal year end. Federal government fiscal year: Oct 1 - Sep 30. States have their own filing requirements.",
  },
  FR: {
    country_code: "FR",
    country_name: "France",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 3 (2nd business day of May) for calendar year companies; 3 months after FY end otherwise",
    vat_filing_frequency: "Monthly (regime reel normal); quarterly (regime reel simplifie); annually (micro-entreprise)",
    annual_report_deadline: "7 months after FY end (filing with Greffe du tribunal de commerce)",
    notes: "Companies may choose non-calendar fiscal year. SAS/SARL must file annual accounts with the commercial court.",
  },
  NL: {
    country_code: "NL",
    country_name: "Netherlands",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "June 1 (5 months after FY end); extension possible to November 1",
    vat_filing_frequency: "Quarterly (default); monthly (if requested or required)",
    annual_report_deadline: "12 months after FY end (small BV/NV); 8 months (medium/large) — filed at KvK",
    notes: "BV/NV may choose non-calendar fiscal year. Late filing penalties are significant.",
  },
  JP: {
    country_code: "JP",
    country_name: "Japan",
    financial_year_start: "04-01",
    financial_year_end: "03-31",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "2 months after fiscal year end; extension to 3 months with approval",
    vat_filing_frequency: "Annually (consumption tax); monthly/quarterly for large companies",
    annual_report_deadline: "3 months after FY end (listed companies); varies for private",
    notes: "Government/most large corporations: Apr 1 - Mar 31. Companies may choose any fiscal year. Consumption tax (10%) filed with corporate tax.",
  },
  AU: {
    country_code: "AU",
    country_name: "Australia",
    financial_year_start: "07-01",
    financial_year_end: "06-30",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "October 31 (individuals); February 28 (companies); later with tax agent",
    vat_filing_frequency: "Quarterly (GST, default); monthly (turnover >20M AUD); annually (<75K AUD)",
    annual_report_deadline: "4 months after FY end (large proprietary); 1 month after AGM (public companies)",
    notes: "Standard Australian financial year: Jul 1 - Jun 30. Companies may apply for substituted accounting period (SAP).",
  },
  IN: {
    country_code: "IN",
    country_name: "India",
    financial_year_start: "04-01",
    financial_year_end: "03-31",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "October 31 (companies requiring audit); September 30 (transfer pricing); July 31 (others)",
    vat_filing_frequency: "Monthly (GST returns GSTR-1/3B); quarterly (QRMP scheme for <5 Cr turnover)",
    annual_report_deadline: "30 days from AGM; AGM within 6 months of FY end (September 30)",
    notes: "All entities must follow Apr 1 - Mar 31 fiscal year. GST replaced multiple indirect taxes in 2017.",
  },
  CA: {
    country_code: "CA",
    country_name: "Canada",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "June 15 (individuals); 6 months after FY end (corporations)",
    vat_filing_frequency: "Quarterly (GST/HST, default); monthly (>6M CAD); annually (<1.5M CAD)",
    annual_report_deadline: "Varies by province; typically annually with Corporations Canada",
    notes: "Corporations may choose any fiscal year end. Individuals must use calendar year. GST/HST rates vary by province.",
  },
  IE: {
    country_code: "IE",
    country_name: "Ireland",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "9 months after accounting period end (corporation tax)",
    vat_filing_frequency: "Bi-monthly (default); quarterly; annually (turnover <3M EUR)",
    annual_report_deadline: "11 months after FY end (filed with CRO)",
    notes: "Companies choose their own accounting period. Corporation tax: 12.5% (trading), 25% (passive). First year return within 9 months of incorporation.",
  },
  ES: {
    country_code: "ES",
    country_name: "Spain",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "July 25 (25 days after 6 months from FY end)",
    vat_filing_frequency: "Quarterly (default); monthly (large companies, >6M EUR turnover)",
    annual_report_deadline: "7 months after FY end (filed with Registro Mercantil within 1 month of AGM)",
    notes: "Companies may choose non-calendar fiscal year. SII (real-time VAT reporting) mandatory for large companies.",
  },
  IT: {
    country_code: "IT",
    country_name: "Italy",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "November 30 (11 months after FY end for calendar year companies)",
    vat_filing_frequency: "Monthly (default); quarterly (turnover <400K EUR services, <700K EUR goods)",
    annual_report_deadline: "120 days after FY end (approval); 30 days after approval (filing with Registro Imprese)",
    notes: "Electronic invoicing (fatturazione elettronica) mandatory for all B2B transactions since 2019.",
  },
  PT: {
    country_code: "PT",
    country_name: "Portugal",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 31 (5 months after FY end, Modelo 22)",
    vat_filing_frequency: "Monthly (turnover >650K EUR); quarterly (default)",
    annual_report_deadline: "July 15 (IES/annual declaration); accounts approved within 3 months of FY end",
    notes: "Companies may choose non-calendar fiscal year with tax authority approval.",
  },
  AT: {
    country_code: "AT",
    country_name: "Austria",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "June 30 (without advisor); April 30 of second following year (with advisor)",
    vat_filing_frequency: "Monthly (turnover >100K EUR); quarterly (default)",
    annual_report_deadline: "9 months after FY end (filed with Firmenbuch)",
    notes: "Companies may choose non-calendar fiscal year. GmbH/AG must file with commercial register.",
  },
  CH: {
    country_code: "CH",
    country_name: "Switzerland",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "9 months after FY end (varies by canton); extensions commonly granted",
    vat_filing_frequency: "Quarterly (default); semi-annually (effective method); monthly (optional)",
    annual_report_deadline: "6 months after FY end (AGM must approve); filing with commercial register",
    notes: "Federal + cantonal + municipal taxes. VAT rate: 8.1% standard. Companies freely choose fiscal year.",
  },
  BE: {
    country_code: "BE",
    country_name: "Belgium",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "7 months after FY end (September 30 for calendar year)",
    vat_filing_frequency: "Monthly (turnover >2.5M EUR); quarterly (default)",
    annual_report_deadline: "7 months after FY end (filed with NBB/Banque Nationale)",
    notes: "Companies may choose non-calendar fiscal year. Extensive VAT reporting requirements.",
  },
  PL: {
    country_code: "PL",
    country_name: "Poland",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "March 31 (3 months after FY end for CIT); June 30 with extension",
    vat_filing_frequency: "Monthly (default for all VAT-registered entities since 2017)",
    annual_report_deadline: "6 months after FY end (approval); 15 days after approval (filing with KRS)",
    notes: "Companies may choose non-calendar fiscal year. JPK_VAT mandatory monthly electronic reporting.",
  },
  CZ: {
    country_code: "CZ",
    country_name: "Czech Republic",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "April 1 (3 months after FY end); July 1 (with tax advisor)",
    vat_filing_frequency: "Monthly (turnover >10M CZK); quarterly (default)",
    annual_report_deadline: "12 months after FY end (filed with commercial register)",
    notes: "Companies may choose non-calendar fiscal year with notification to tax office.",
  },
  HU: {
    country_code: "HU",
    country_name: "Hungary",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 31 (5 months after FY end)",
    vat_filing_frequency: "Monthly (default); quarterly (turnover <50M HUF); annually (<5M HUF)",
    annual_report_deadline: "May 31 (calendar year); 5 months after FY end (filed with court of registration)",
    notes: "9% corporate income tax rate — one of the lowest in the EU. Companies may choose non-calendar fiscal year.",
  },
  RO: {
    country_code: "RO",
    country_name: "Romania",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "March 25 (annual CIT declaration); June 25 (annual financial statements)",
    vat_filing_frequency: "Monthly (default); quarterly (turnover <100K EUR)",
    annual_report_deadline: "150 days after FY end (filed with trade register/ANAF)",
    notes: "Calendar year mandatory for most companies. Micro-enterprise regime for companies with turnover <500K EUR.",
  },
  SK: {
    country_code: "SK",
    country_name: "Slovakia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "March 31 (3 months after FY end); extension to June 30 or September 30",
    vat_filing_frequency: "Monthly (first 12 months after registration); quarterly (turnover <100K EUR)",
    annual_report_deadline: "6 months after FY end (filed with commercial register)",
    notes: "Companies may choose non-calendar fiscal year. 21% CIT rate.",
  },
  BG: {
    country_code: "BG",
    country_name: "Bulgaria",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "June 30 (annual CIT return)",
    vat_filing_frequency: "Monthly (all VAT-registered entities)",
    annual_report_deadline: "September 30 (filed with commercial register)",
    notes: "Calendar year mandatory. 10% flat CIT rate — lowest in the EU.",
  },
  HR: {
    country_code: "HR",
    country_name: "Croatia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "April 30 (4 months after FY end)",
    vat_filing_frequency: "Monthly (turnover >800K HRK); quarterly (default)",
    annual_report_deadline: "June 30 (filed with FINA)",
    notes: "Calendar year required. Joined eurozone January 2023. CIT: 10% (turnover <1M EUR), 18% otherwise.",
  },
  SI: {
    country_code: "SI",
    country_name: "Slovenia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "March 31 (3 months after FY end)",
    vat_filing_frequency: "Monthly (turnover >210K EUR); quarterly (default)",
    annual_report_deadline: "March 31 (filed with AJPES)",
    notes: "Calendar year mandatory for most entities. 19% CIT rate.",
  },
  EE: {
    country_code: "EE",
    country_name: "Estonia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "N/A (CIT only on distributed profits — 20% on distribution)",
    vat_filing_frequency: "Monthly (all VAT-registered entities; due 20th of following month)",
    annual_report_deadline: "6 months after FY end (filed with Centre of Registers)",
    notes: "Unique CIT system: 0% on reinvested profits, 20% on distributions. Companies may choose non-calendar fiscal year.",
  },
  LV: {
    country_code: "LV",
    country_name: "Latvia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "4 months after FY end (CIT); monthly CIT prepayments abolished 2018",
    vat_filing_frequency: "Monthly (all VAT-registered entities)",
    annual_report_deadline: "4 months after FY end (filed with Enterprise Register)",
    notes: "Similar to Estonia: 20% CIT on distributed profits only (since 2018). Calendar year standard.",
  },
  LT: {
    country_code: "LT",
    country_name: "Lithuania",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "June 15 (CIT return for calendar year companies)",
    vat_filing_frequency: "Monthly (default); quarterly (turnover <300K EUR)",
    annual_report_deadline: "4 months after FY end (filed with Centre of Registers)",
    notes: "15% standard CIT rate; 5% for small companies (turnover <300K EUR, <10 employees).",
  },
  LU: {
    country_code: "LU",
    country_name: "Luxembourg",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 31 (calendar year); extension to August 31 commonly granted",
    vat_filing_frequency: "Monthly (turnover >620K EUR); quarterly (112-620K EUR); annually (<112K EUR)",
    annual_report_deadline: "7 months after FY end (filed with RCS/Registre de Commerce)",
    notes: "Companies may choose non-calendar fiscal year. Complex holding company rules (SOPARFI).",
  },
  MT: {
    country_code: "MT",
    country_name: "Malta",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "9 months after FY end",
    vat_filing_frequency: "Quarterly (default); monthly (large enterprises)",
    annual_report_deadline: "10 months after FY end (filed with Malta Business Registry)",
    notes: "35% CIT rate with imputation system; effective rate can be 5% with refund mechanism.",
  },
  CY: {
    country_code: "CY",
    country_name: "Cyprus",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "15 months after FY end (electronic filing)",
    vat_filing_frequency: "Quarterly (all VAT-registered entities)",
    annual_report_deadline: "12 months after FY end (filed with Registrar of Companies)",
    notes: "12.5% CIT rate. Companies may choose non-calendar fiscal year. IP box regime with 2.5% effective rate.",
  },
  SG: {
    country_code: "SG",
    country_name: "Singapore",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "November 30 (CIT Form C/C-S); estimated tax: 3 months after FY end",
    vat_filing_frequency: "Quarterly (GST returns; rate 9% from 2024)",
    annual_report_deadline: "5 months after FY end (AGM); 7 months (XBRL filing with ACRA)",
    notes: "17% CIT rate with partial exemption scheme. Companies freely choose fiscal year end.",
  },
  HK: {
    country_code: "HK",
    country_name: "Hong Kong",
    financial_year_start: "04-01",
    financial_year_end: "03-31",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "1 month from date of issue of profits tax return (extensions by BIR category)",
    vat_filing_frequency: "N/A (no VAT/GST in Hong Kong)",
    annual_report_deadline: "42 days after AGM (annual return to Companies Registry)",
    notes: "16.5% standard profits tax; 8.25% on first 2M HKD. Companies may choose any FY end. Territorial basis of taxation.",
  },
  NZ: {
    country_code: "NZ",
    country_name: "New Zealand",
    financial_year_start: "04-01",
    financial_year_end: "03-31",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "July 7 (without tax agent); March 31 of following year (with agent, extensions vary)",
    vat_filing_frequency: "Monthly (GST, turnover >24M NZD); bi-monthly (default); 6-monthly (<500K NZD)",
    annual_report_deadline: "5 months after balance date (annual return to Companies Office)",
    notes: "Standard income year: Apr 1 - Mar 31. Companies may apply for a non-standard balance date. 28% CIT rate.",
  },
  BR: {
    country_code: "BR",
    country_name: "Brazil",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "July 31 (IRPJ/CSLL annual; monthly prepayments required)",
    vat_filing_frequency: "Monthly (ICMS, IPI, PIS, COFINS — multiple indirect taxes)",
    annual_report_deadline: "April 30 (filing with Junta Comercial); large companies publish in official gazette",
    notes: "Calendar year mandatory for tax purposes. Complex tax system with federal, state, and municipal taxes. Tax reform pending.",
  },
  MX: {
    country_code: "MX",
    country_name: "Mexico",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "March 31 (corporate); April 30 (individual)",
    vat_filing_frequency: "Monthly (IVA returns, due 17th of following month)",
    annual_report_deadline: "March 31 (filed with SAT); varies for public companies (CNBV)",
    notes: "Calendar year mandatory. 30% CIT rate. CFDI electronic invoicing mandatory for all transactions.",
  },
  KR: {
    country_code: "KR",
    country_name: "South Korea",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "3 months after FY end (March 31 for calendar year companies)",
    vat_filing_frequency: "Quarterly (with monthly preliminary returns for large corporations)",
    annual_report_deadline: "90 days after FY end (external audit report); filed with FSS if listed",
    notes: "Companies may choose non-calendar fiscal year. Progressive CIT: 9-24% depending on taxable income brackets.",
  },
  CN: {
    country_code: "CN",
    country_name: "China",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 31 (annual CIT settlement); monthly/quarterly prepayments within 15 days",
    vat_filing_frequency: "Monthly (general taxpayers); quarterly (small-scale taxpayers)",
    annual_report_deadline: "June 30 (annual report filed with SAMR/AIC)",
    notes: "Calendar year mandatory. 25% standard CIT rate; 15% for HNTE (high-tech enterprises). VAT reform ongoing.",
  },
  ZA: {
    country_code: "ZA",
    country_name: "South Africa",
    financial_year_start: "03-01",
    financial_year_end: "02-28",
    fiscal_year_matches_calendar: false,
    tax_filing_deadline: "12 months after FY end (provisional tax at 6-month intervals)",
    vat_filing_frequency: "Bi-monthly (default); monthly (turnover >30M ZAR)",
    annual_report_deadline: "30 business days after AGM (filed with CIPC); 6 months after FY end for tax",
    notes: "Government fiscal year: Apr 1 - Mar 31. Companies choose their own FY end. 27% CIT rate.",
  },
  IL: {
    country_code: "IL",
    country_name: "Israel",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "May 31 (5 months after FY end); extension to November 30 with representation",
    vat_filing_frequency: "Monthly (turnover >1.5M ILS); bi-monthly (default)",
    annual_report_deadline: "Varies; filed with Companies Registrar annually",
    notes: "Calendar year standard. 23% CIT rate. VAT rate: 17%.",
  },
  AE: {
    country_code: "AE",
    country_name: "United Arab Emirates",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "9 months after FY end (corporate tax introduced June 2023 at 9%)",
    vat_filing_frequency: "Quarterly (default); monthly (if directed by FTA)",
    annual_report_deadline: "Varies by free zone / mainland authority; typically 6 months after FY end",
    notes: "9% CIT effective June 2023 (0% on first 375K AED). VAT at 5% since 2018. Free zones may retain 0% CIT for qualifying income.",
  },
  SA: {
    country_code: "SA",
    country_name: "Saudi Arabia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "120 days after FY end (April 30 for calendar year)",
    vat_filing_frequency: "Monthly (turnover >40M SAR); quarterly (default)",
    annual_report_deadline: "6 months after FY end (filed with Ministry of Commerce)",
    notes: "20% CIT on foreign-owned entities; 2.5% zakat on Saudi/GCC-owned. VAT rate: 15%.",
  },
  MY: {
    country_code: "MY",
    country_name: "Malaysia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "7 months after FY end (Form C); monthly installment estimates (CP204)",
    vat_filing_frequency: "Bi-monthly (Sales Tax/Service Tax); no VAT/GST currently",
    annual_report_deadline: "30 days after AGM (filed with SSM/Companies Commission)",
    notes: "Companies freely choose FY end. 24% CIT rate (17% on first 600K MYR for SMEs). Sales & Service Tax replaced GST in 2018.",
  },
  TH: {
    country_code: "TH",
    country_name: "Thailand",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "150 days after FY end (May 31 for calendar year); mid-year return at month 8",
    vat_filing_frequency: "Monthly (due 15th of following month)",
    annual_report_deadline: "5 months after FY end (filed with DBD/Department of Business Development)",
    notes: "20% CIT rate. VAT rate: 7% (reduced from 10% statutory rate). Calendar year standard but companies may request different FY.",
  },
  ID: {
    country_code: "ID",
    country_name: "Indonesia",
    financial_year_start: "01-01",
    financial_year_end: "12-31",
    fiscal_year_matches_calendar: true,
    tax_filing_deadline: "4 months after FY end (April 30 for calendar year); extension of 2 months possible",
    vat_filing_frequency: "Monthly (due end of following month)",
    annual_report_deadline: "6 months after FY end (filed with Ministry of Law and Human Rights)",
    notes: "22% CIT rate. Calendar year mandatory for tax purposes (bookkeeping year may differ with approval). VAT rate: 11%.",
  },
};

// ISO 3166-1 alpha-2 to common name mapping for the lookup
const COUNTRY_NAME_MAP: Record<string, string> = {};
for (const [code, info] of Object.entries(FISCAL_YEAR_DATA)) {
  COUNTRY_NAME_MAP[info.country_name.toUpperCase()] = code;
}

registerCapability("financial-year-dates", async (input: CapabilityInput) => {
  let rawCountry =
    (input.country_code as string) ??
    (input.country as string) ??
    (input.task as string) ??
    "";

  if (typeof rawCountry !== "string" || !rawCountry.trim()) {
    throw new Error(
      "'country_code' or 'country' is required. Provide a 2-letter ISO country code (e.g. SE, GB, US) or country name.",
    );
  }

  const cleaned = rawCountry.trim();

  // Try as country code first (2 letters)
  let code = cleaned.toUpperCase();
  if (code.length !== 2 || !FISCAL_YEAR_DATA[code]) {
    // Try matching by country name
    const nameKey = cleaned.toUpperCase();
    const found = COUNTRY_NAME_MAP[nameKey];
    if (found) {
      code = found;
    } else {
      // Fuzzy match: check if input contains or is contained by a country name
      const match = Object.entries(COUNTRY_NAME_MAP).find(
        ([name]) =>
          name.includes(nameKey) || nameKey.includes(name),
      );
      if (match) {
        code = match[1];
      }
    }
  }

  const data = FISCAL_YEAR_DATA[code];
  if (!data) {
    const supported = Object.entries(FISCAL_YEAR_DATA)
      .map(([c, info]) => `${c} (${info.country_name})`)
      .join(", ");
    throw new Error(
      `Country '${cleaned}' not found. Supported countries: ${supported}`,
    );
  }

  return {
    output: {
      country_code: data.country_code,
      country_name: data.country_name,
      financial_year_start: data.financial_year_start,
      financial_year_end: data.financial_year_end,
      fiscal_year_matches_calendar: data.fiscal_year_matches_calendar,
      tax_filing_deadline: data.tax_filing_deadline,
      vat_filing_frequency: data.vat_filing_frequency,
      annual_report_deadline: data.annual_report_deadline,
      notes: data.notes,
    },
    provenance: {
      source: "algorithmic",
      fetched_at: new Date().toISOString(),
    },
  };
});
