/**
 * `image-resize` behaviour across the sharp 0.34.5 → 0.35.3 upgrade.
 *
 * ## Why this file did not exist before, and why it does now
 *
 * VERIFY-DEP / WP13 triage, 2026-08-25. `sharp@0.34.5` carries inherited
 * libvips CVEs (2026-33327, -33328, -35590, -35591) — memory-safety issues in
 * image decoders. `image-resize.ts:41` calls `sharp(imageBuffer)` on bytes the
 * caller supplies, either by URL or base64, and the capability is
 * `x402_enabled`, so **no signup and no API key are required**: payment is the
 * auth. That is the worst exposure profile in the whole scan.
 *
 * The fix is `sharp@0.35.3`, which is a semver-major bump AND a change of
 * native artifact (libvips 8.17.3 → 8.18.3). Before this file, the capability
 * had no behavioural coverage at all — `ssrf-bucket-a.test.ts` exercises its
 * URL-fetch path for SSRF, and nothing checked that a resize produces the
 * dimensions, format, or metadata it claims. Upgrading a native image decoder
 * with no output assertions is how silent drift ships.
 *
 * ## What was measured before writing this
 *
 * Both versions were run side by side, in separate processes (two sharp
 * natives cannot coexist in one process — the second `dlopen` fails), over 19
 * cases: all five `fit` modes × three output formats, plus width-only,
 * height-only, a 400×400 upscale at quality 50, and a 1×1 degenerate case.
 *
 *   - **Zero drift** in width, height, format, or channel count. 19 of 19.
 *   - Identical error text on undecodable input:
 *     `Input buffer contains unsupported image format`.
 *   - Three PNG cases differ by exactly one byte (298→297, 393→392, 179→178).
 *     PNG encoder output, not a behaviour change — but `size_bytes` is in the
 *     response, so it is recorded rather than glossed.
 *
 * That sweep was a one-off harness, not this file. **This file does not
 * reproduce all 19 cases**, and an earlier version of this comment implied it
 * did. What it pins is the subset that a future sharp bump could plausibly
 * break: geometry and content per fit mode, format and channel round-trip,
 * both input paths, and the refusal text. It deliberately does NOT pin byte
 * sizes — those would fail on every encoder revision while proving nothing
 * about correctness.
 *
 * ## What this file does not cover, stated rather than implied
 *
 * The source image is generated by the same sharp under test, so this cannot
 * detect a decoder incompatibility with real-world files. There is no EXIF
 * orientation fixture, no ICC-profile fixture, and no animated input. Those
 * would need committed binary fixtures, which is a larger change than a
 * dependency bump should carry.
 */

import { describe, expect, it } from "vitest";
import sharp from "sharp";
import "./image-resize.js";
import { getExecutor } from "./index.js";

const run = () => getExecutor("image-resize")!;

type ResizeOutput = {
  output: {
    base64: string;
    content_type: string;
    width: number;
    height: number;
    size_bytes: number;
    format: string;
  };
};

/**
 * A deterministic source image: 320×240, blue, with a red stripe across the
 * top 16 rows.
 *
 * The stripe is what makes the `fit` tests mean anything. The first version of
 * this file used a uniform fill, and `cover`, `contain` and `fill` all resolve
 * a 4:3 source into a 5:3 box at exactly 100×60 — so all three tests asserted
 * the same two numbers, and an implementation that ignored `fit` entirely and
 * always used `cover` would have passed every one of them. Reviewer-found. A
 * uniform image also cannot detect crop, stretch or kernel drift, which is
 * most of what a native decoder upgrade could plausibly break.
 *
 * With the stripe, each fit leaves a distinct signature (measured):
 *
 *   cover   100×60  top-left blue   top-centre BLUE   — stripe cropped away
 *   contain 100×60  top-left BLACK  top-centre red    — pillarbox padding
 *   fill    100×60  top-left RED    top-centre red    — stretched full width
 */
const SRC_W = 320;
const SRC_H = 240;
const STRIPE_H = 16;
const RED = [255, 0, 0];
const BLUE = [0, 0, 255];
const PAD = [0, 0, 0];

async function sourcePng(): Promise<Buffer> {
  const raw = Buffer.alloc(SRC_W * SRC_H * 3);
  for (let y = 0; y < SRC_H; y++) {
    for (let x = 0; x < SRC_W; x++) {
      const i = (y * SRC_W + x) * 3;
      const [r, g, b] = y < STRIPE_H ? RED : BLUE;
      raw[i] = r!;
      raw[i + 1] = g!;
      raw[i + 2] = b!;
    }
  }
  return sharp(raw, { raw: { width: SRC_W, height: SRC_H, channels: 3 } }).png().toBuffer();
}

/** Decode a returned base64 payload and read one pixel's RGB. */
async function pixelOf(base64: string, x: number, y: number): Promise<number[]> {
  const { data, info } = await sharp(Buffer.from(base64, "base64"))
    .raw()
    .toBuffer({ resolveWithObject: true });
  const i = (y * info.width + x) * info.channels;
  return [...data.slice(i, i + 3)];
}

describe("image-resize: the native decoder is the one we think it is", () => {
  it("runs a libvips at or above the version that carries the CVE fixes", () => {
    // The whole point of the upgrade. sharp's own version is not enough —
    // the CVEs are in libvips, which ships as a separate prebuilt artifact.
    //
    // The patch component is compared, not just major/minor. The first version
    // of this assertion stopped at 8.18, which would have accepted 8.18.0,
    // 8.18.1 and 8.18.2 — all below the 8.18.3 floor the advisory names.
    // Reviewer-found. It happened to discriminate this particular 8.17.3 →
    // 8.18.3 upgrade, which is exactly how a too-loose floor survives review.
    const [maj, min, patch] = sharp.versions.vips.split(".").map(Number);
    const atLeast = (a: number, b: number, c: number) =>
      maj! > a || (maj === a && (min! > b || (min === b && patch! >= c)));
    expect(
      atLeast(8, 18, 3),
      `libvips ${sharp.versions.vips} is below the 8.18.3 floor named in the advisory`,
    ).toBe(true);
  });
});

describe("image-resize: fit modes produce the geometry AND the content they claim", () => {
  // Measured identical on 0.34.5 and 0.35.3. Source is 320x240 (4:3),
  // requested 100x60 (5:3). Three of the five resolve to the same 100x60 box,
  // so geometry alone cannot tell them apart — each case therefore pins a
  // pixel that only the correct fit produces.
  const cases: Array<{
    fit: string;
    width: number;
    height: number;
    probe: { x: number; y: number; expect: number[]; why: string };
  }> = [
    {
      fit: "cover",
      width: 100,
      height: 60,
      probe: { x: 50, y: 0, expect: BLUE, why: "cover crops the top; the red stripe is gone" },
    },
    {
      fit: "contain",
      width: 100,
      height: 60,
      probe: { x: 0, y: 30, expect: PAD, why: "contain pillarboxes; the left edge is padding" },
    },
    {
      fit: "fill",
      width: 100,
      height: 60,
      probe: { x: 0, y: 0, expect: RED, why: "fill stretches; the stripe spans the full width" },
    },
    {
      fit: "inside",
      width: 80,
      height: 60,
      probe: { x: 0, y: 0, expect: RED, why: "inside preserves aspect and does not pad" },
    },
    {
      fit: "outside",
      width: 100,
      height: 75,
      probe: { x: 0, y: 0, expect: RED, why: "outside preserves aspect and covers" },
    },
  ];

  for (const c of cases) {
    it(`fit=${c.fit} yields ${c.width}x${c.height} and ${c.probe.why}`, async () => {
      const base64 = (await sourcePng()).toString("base64");
      const r = (await run()({
        base64,
        target_width: 100,
        target_height: 60,
        fit: c.fit,
        format: "png",
      })) as ResizeOutput;

      expect(r.output.width).toBe(c.width);
      expect(r.output.height).toBe(c.height);
      expect(
        await pixelOf(r.output.base64, c.probe.x, c.probe.y),
        `fit=${c.fit}: ${c.probe.why}`,
      ).toEqual(c.probe.expect);
    });
  }

  it("channel count survives the round trip", async () => {
    // Asserted because the cross-version sweep compared channels; without this
    // the suite claimed a property it never checked.
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({
      base64,
      target_width: 100,
      target_height: 60,
      format: "png",
    })) as ResizeOutput;
    const md = await sharp(Buffer.from(r.output.base64, "base64")).metadata();
    expect(md.channels).toBe(3);
  });

  it("width-only preserves aspect ratio", async () => {
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({ base64, target_width: 120, format: "png" })) as ResizeOutput;
    expect(r.output.width).toBe(120);
    expect(r.output.height).toBe(90); // 320x240 -> 4:3
  });

  it("height-only preserves aspect ratio", async () => {
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({ base64, target_height: 90, format: "jpeg" })) as ResizeOutput;
    expect(r.output.width).toBe(120);
    expect(r.output.height).toBe(90);
  });
});

describe("image-resize: output formats and their declared metadata", () => {
  const formats: Array<{ format: string; mime: string }> = [
    { format: "png", mime: "image/png" },
    { format: "jpeg", mime: "image/jpeg" },
    { format: "webp", mime: "image/webp" },
  ];

  for (const f of formats) {
    it(`${f.format} declares ${f.mime} and really is ${f.format}`, async () => {
      const base64 = (await sourcePng()).toString("base64");
      const r = (await run()({
        base64,
        target_width: 100,
        target_height: 60,
        format: f.format,
      })) as ResizeOutput;

      expect(r.output.format).toBe(f.format);
      expect(r.output.content_type).toBe(f.mime);

      // The declared content type must match the actual bytes. Checking the
      // returned field against itself would pass on any encoder regression.
      const decoded = await sharp(Buffer.from(r.output.base64, "base64")).metadata();
      expect(decoded.format).toBe(f.format);
      expect(decoded.width).toBe(r.output.width);
      expect(decoded.height).toBe(r.output.height);
    });
  }

  it("size_bytes matches the payload actually returned", async () => {
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({
      base64,
      target_width: 50,
      target_height: 50,
      format: "png",
    })) as ResizeOutput;
    expect(r.output.size_bytes).toBe(Buffer.from(r.output.base64, "base64").length);
  });
});

describe("image-resize: both input paths", () => {
  it("accepts a bare base64 payload", async () => {
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({ base64, target_width: 50, target_height: 50 })) as ResizeOutput;
    expect(r.output.width).toBe(50);
    expect(r.output.height).toBe(50);
  });

  it("accepts a data: URI and strips the prefix", async () => {
    const base64 = (await sourcePng()).toString("base64");
    const r = (await run()({
      base64: `data:image/png;base64,${base64}`,
      target_width: 50,
      target_height: 50,
    })) as ResizeOutput;
    expect(r.output.width).toBe(50);
  });

  it("fetches image_url through safeFetch and resizes the response", async () => {
    // The URL path, stubbed at fetch so the test stays hermetic. safeFetch's
    // own SSRF behaviour is covered by ssrf-bucket-a.test.ts; what matters
    // here is that fetched bytes reach the decoder and come back resized.
    const png = await sourcePng();
    const original = globalThis.fetch;
    globalThis.fetch = (async () =>
      new Response(new Uint8Array(png), {
        status: 200,
        headers: { "Content-Type": "image/png" },
      })) as typeof fetch;
    try {
      const r = (await run()({
        image_url: "https://example.com/a.png",
        target_width: 64,
        target_height: 64,
      })) as ResizeOutput;
      expect(r.output.width).toBe(64);
      expect(r.output.height).toBe(64);
    } finally {
      globalThis.fetch = original;
    }
  });
});

describe("image-resize: refusals", () => {
  it("refuses undecodable bytes with a stable message", async () => {
    // Identical text on 0.34.5 and 0.35.3 — verified before the upgrade,
    // because this string reaches the caller through sanitizeFailureReason.
    const base64 = Buffer.from("this is definitely not an image").toString("base64");
    await expect(
      run()({ base64, target_width: 10, target_height: 10 }),
    ).rejects.toThrow(/unsupported image format/i);
  });

  it("requires an input", async () => {
    await expect(run()({ target_width: 10 })).rejects.toThrow(
      /'image_url' or 'base64' is required/,
    );
  });

  it("requires a target dimension", async () => {
    const base64 = (await sourcePng()).toString("base64");
    await expect(run()({ base64 })).rejects.toThrow(
      /'target_width' or 'target_height' is required/,
    );
  });
});
