import { registerCapability, type CapabilityInput } from "./index.js";

// ─── ISO 3166-1 Country Lookup — complete algorithmic database ──────────────

interface CountryEntry {
  name: string;
  alpha_2: string;
  alpha_3: string;
  numeric: string;
  region: string;
  subregion: string;
  capital: string;
  currency_code: string;
  currency_name: string;
  calling_code: string;
  tld: string;
  languages: string[];
  eu_member: boolean;
  schengen: boolean;
  eurozone: boolean;
  un_member: boolean;
}

const EU_MEMBERS = new Set(["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"]);
const SCHENGEN = new Set(["AT","BE","CZ","DK","EE","FI","FR","DE","GR","HU","IS","IT","LV","LI","LT","LU","MT","NL","NO","PL","PT","SK","SI","ES","SE","CH","HR"]);
const EUROZONE = new Set(["AT","BE","CY","EE","FI","FR","DE","GR","IE","IT","LV","LT","LU","MT","NL","PT","SK","SI","ES","HR"]);

// All 249 ISO 3166-1 entries
const COUNTRIES: CountryEntry[] = [
  { name: "Afghanistan", alpha_2: "AF", alpha_3: "AFG", numeric: "004", region: "Asia", subregion: "Southern Asia", capital: "Kabul", currency_code: "AFN", currency_name: "Afghan Afghani", calling_code: "+93", tld: ".af", languages: ["Pashto", "Dari"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Albania", alpha_2: "AL", alpha_3: "ALB", numeric: "008", region: "Europe", subregion: "Southern Europe", capital: "Tirana", currency_code: "ALL", currency_name: "Albanian Lek", calling_code: "+355", tld: ".al", languages: ["Albanian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Algeria", alpha_2: "DZ", alpha_3: "DZA", numeric: "012", region: "Africa", subregion: "Northern Africa", capital: "Algiers", currency_code: "DZD", currency_name: "Algerian Dinar", calling_code: "+213", tld: ".dz", languages: ["Arabic", "Berber"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "American Samoa", alpha_2: "AS", alpha_3: "ASM", numeric: "016", region: "Oceania", subregion: "Polynesia", capital: "Pago Pago", currency_code: "USD", currency_name: "US Dollar", calling_code: "+1-684", tld: ".as", languages: ["English", "Samoan"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Andorra", alpha_2: "AD", alpha_3: "AND", numeric: "020", region: "Europe", subregion: "Southern Europe", capital: "Andorra la Vella", currency_code: "EUR", currency_name: "Euro", calling_code: "+376", tld: ".ad", languages: ["Catalan"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Angola", alpha_2: "AO", alpha_3: "AGO", numeric: "024", region: "Africa", subregion: "Middle Africa", capital: "Luanda", currency_code: "AOA", currency_name: "Angolan Kwanza", calling_code: "+244", tld: ".ao", languages: ["Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Anguilla", alpha_2: "AI", alpha_3: "AIA", numeric: "660", region: "Americas", subregion: "Caribbean", capital: "The Valley", currency_code: "XCD", currency_name: "East Caribbean Dollar", calling_code: "+1-264", tld: ".ai", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Antarctica", alpha_2: "AQ", alpha_3: "ATA", numeric: "010", region: "", subregion: "", capital: "", currency_code: "", currency_name: "", calling_code: "+672", tld: ".aq", languages: [], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Antigua and Barbuda", alpha_2: "AG", alpha_3: "ATG", numeric: "028", region: "Americas", subregion: "Caribbean", capital: "St. John's", currency_code: "XCD", currency_name: "East Caribbean Dollar", calling_code: "+1-268", tld: ".ag", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Argentina", alpha_2: "AR", alpha_3: "ARG", numeric: "032", region: "Americas", subregion: "South America", capital: "Buenos Aires", currency_code: "ARS", currency_name: "Argentine Peso", calling_code: "+54", tld: ".ar", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Armenia", alpha_2: "AM", alpha_3: "ARM", numeric: "051", region: "Asia", subregion: "Western Asia", capital: "Yerevan", currency_code: "AMD", currency_name: "Armenian Dram", calling_code: "+374", tld: ".am", languages: ["Armenian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Aruba", alpha_2: "AW", alpha_3: "ABW", numeric: "533", region: "Americas", subregion: "Caribbean", capital: "Oranjestad", currency_code: "AWG", currency_name: "Aruban Florin", calling_code: "+297", tld: ".aw", languages: ["Dutch", "Papiamento"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Australia", alpha_2: "AU", alpha_3: "AUS", numeric: "036", region: "Oceania", subregion: "Australia and New Zealand", capital: "Canberra", currency_code: "AUD", currency_name: "Australian Dollar", calling_code: "+61", tld: ".au", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Austria", alpha_2: "AT", alpha_3: "AUT", numeric: "040", region: "Europe", subregion: "Western Europe", capital: "Vienna", currency_code: "EUR", currency_name: "Euro", calling_code: "+43", tld: ".at", languages: ["German"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Azerbaijan", alpha_2: "AZ", alpha_3: "AZE", numeric: "031", region: "Asia", subregion: "Western Asia", capital: "Baku", currency_code: "AZN", currency_name: "Azerbaijani Manat", calling_code: "+994", tld: ".az", languages: ["Azerbaijani"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bahamas", alpha_2: "BS", alpha_3: "BHS", numeric: "044", region: "Americas", subregion: "Caribbean", capital: "Nassau", currency_code: "BSD", currency_name: "Bahamian Dollar", calling_code: "+1-242", tld: ".bs", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bahrain", alpha_2: "BH", alpha_3: "BHR", numeric: "048", region: "Asia", subregion: "Western Asia", capital: "Manama", currency_code: "BHD", currency_name: "Bahraini Dinar", calling_code: "+973", tld: ".bh", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bangladesh", alpha_2: "BD", alpha_3: "BGD", numeric: "050", region: "Asia", subregion: "Southern Asia", capital: "Dhaka", currency_code: "BDT", currency_name: "Bangladeshi Taka", calling_code: "+880", tld: ".bd", languages: ["Bengali"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Barbados", alpha_2: "BB", alpha_3: "BRB", numeric: "052", region: "Americas", subregion: "Caribbean", capital: "Bridgetown", currency_code: "BBD", currency_name: "Barbadian Dollar", calling_code: "+1-246", tld: ".bb", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Belarus", alpha_2: "BY", alpha_3: "BLR", numeric: "112", region: "Europe", subregion: "Eastern Europe", capital: "Minsk", currency_code: "BYN", currency_name: "Belarusian Ruble", calling_code: "+375", tld: ".by", languages: ["Belarusian", "Russian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Belgium", alpha_2: "BE", alpha_3: "BEL", numeric: "056", region: "Europe", subregion: "Western Europe", capital: "Brussels", currency_code: "EUR", currency_name: "Euro", calling_code: "+32", tld: ".be", languages: ["Dutch", "French", "German"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Belize", alpha_2: "BZ", alpha_3: "BLZ", numeric: "084", region: "Americas", subregion: "Central America", capital: "Belmopan", currency_code: "BZD", currency_name: "Belize Dollar", calling_code: "+501", tld: ".bz", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Benin", alpha_2: "BJ", alpha_3: "BEN", numeric: "204", region: "Africa", subregion: "Western Africa", capital: "Porto-Novo", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+229", tld: ".bj", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bermuda", alpha_2: "BM", alpha_3: "BMU", numeric: "060", region: "Americas", subregion: "Northern America", capital: "Hamilton", currency_code: "BMD", currency_name: "Bermudian Dollar", calling_code: "+1-441", tld: ".bm", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Bhutan", alpha_2: "BT", alpha_3: "BTN", numeric: "064", region: "Asia", subregion: "Southern Asia", capital: "Thimphu", currency_code: "BTN", currency_name: "Bhutanese Ngultrum", calling_code: "+975", tld: ".bt", languages: ["Dzongkha"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bolivia", alpha_2: "BO", alpha_3: "BOL", numeric: "068", region: "Americas", subregion: "South America", capital: "Sucre", currency_code: "BOB", currency_name: "Bolivian Boliviano", calling_code: "+591", tld: ".bo", languages: ["Spanish", "Quechua", "Aymara"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bosnia and Herzegovina", alpha_2: "BA", alpha_3: "BIH", numeric: "070", region: "Europe", subregion: "Southern Europe", capital: "Sarajevo", currency_code: "BAM", currency_name: "Bosnia-Herzegovina Convertible Mark", calling_code: "+387", tld: ".ba", languages: ["Bosnian", "Croatian", "Serbian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Botswana", alpha_2: "BW", alpha_3: "BWA", numeric: "072", region: "Africa", subregion: "Southern Africa", capital: "Gaborone", currency_code: "BWP", currency_name: "Botswana Pula", calling_code: "+267", tld: ".bw", languages: ["English", "Tswana"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Brazil", alpha_2: "BR", alpha_3: "BRA", numeric: "076", region: "Americas", subregion: "South America", capital: "Brasília", currency_code: "BRL", currency_name: "Brazilian Real", calling_code: "+55", tld: ".br", languages: ["Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Brunei", alpha_2: "BN", alpha_3: "BRN", numeric: "096", region: "Asia", subregion: "South-Eastern Asia", capital: "Bandar Seri Begawan", currency_code: "BND", currency_name: "Brunei Dollar", calling_code: "+673", tld: ".bn", languages: ["Malay"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Bulgaria", alpha_2: "BG", alpha_3: "BGR", numeric: "100", region: "Europe", subregion: "Eastern Europe", capital: "Sofia", currency_code: "BGN", currency_name: "Bulgarian Lev", calling_code: "+359", tld: ".bg", languages: ["Bulgarian"], eu_member: true, schengen: false, eurozone: false, un_member: true },
  { name: "Burkina Faso", alpha_2: "BF", alpha_3: "BFA", numeric: "854", region: "Africa", subregion: "Western Africa", capital: "Ouagadougou", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+226", tld: ".bf", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Burundi", alpha_2: "BI", alpha_3: "BDI", numeric: "108", region: "Africa", subregion: "Eastern Africa", capital: "Gitega", currency_code: "BIF", currency_name: "Burundian Franc", calling_code: "+257", tld: ".bi", languages: ["Kirundi", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Cabo Verde", alpha_2: "CV", alpha_3: "CPV", numeric: "132", region: "Africa", subregion: "Western Africa", capital: "Praia", currency_code: "CVE", currency_name: "Cape Verdean Escudo", calling_code: "+238", tld: ".cv", languages: ["Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Cambodia", alpha_2: "KH", alpha_3: "KHM", numeric: "116", region: "Asia", subregion: "South-Eastern Asia", capital: "Phnom Penh", currency_code: "KHR", currency_name: "Cambodian Riel", calling_code: "+855", tld: ".kh", languages: ["Khmer"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Cameroon", alpha_2: "CM", alpha_3: "CMR", numeric: "120", region: "Africa", subregion: "Middle Africa", capital: "Yaoundé", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+237", tld: ".cm", languages: ["French", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Canada", alpha_2: "CA", alpha_3: "CAN", numeric: "124", region: "Americas", subregion: "Northern America", capital: "Ottawa", currency_code: "CAD", currency_name: "Canadian Dollar", calling_code: "+1", tld: ".ca", languages: ["English", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Central African Republic", alpha_2: "CF", alpha_3: "CAF", numeric: "140", region: "Africa", subregion: "Middle Africa", capital: "Bangui", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+236", tld: ".cf", languages: ["French", "Sango"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Chad", alpha_2: "TD", alpha_3: "TCD", numeric: "148", region: "Africa", subregion: "Middle Africa", capital: "N'Djamena", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+235", tld: ".td", languages: ["French", "Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Chile", alpha_2: "CL", alpha_3: "CHL", numeric: "152", region: "Americas", subregion: "South America", capital: "Santiago", currency_code: "CLP", currency_name: "Chilean Peso", calling_code: "+56", tld: ".cl", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "China", alpha_2: "CN", alpha_3: "CHN", numeric: "156", region: "Asia", subregion: "Eastern Asia", capital: "Beijing", currency_code: "CNY", currency_name: "Chinese Yuan", calling_code: "+86", tld: ".cn", languages: ["Mandarin Chinese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Colombia", alpha_2: "CO", alpha_3: "COL", numeric: "170", region: "Americas", subregion: "South America", capital: "Bogotá", currency_code: "COP", currency_name: "Colombian Peso", calling_code: "+57", tld: ".co", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Comoros", alpha_2: "KM", alpha_3: "COM", numeric: "174", region: "Africa", subregion: "Eastern Africa", capital: "Moroni", currency_code: "KMF", currency_name: "Comorian Franc", calling_code: "+269", tld: ".km", languages: ["Comorian", "Arabic", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Congo (Democratic Republic)", alpha_2: "CD", alpha_3: "COD", numeric: "180", region: "Africa", subregion: "Middle Africa", capital: "Kinshasa", currency_code: "CDF", currency_name: "Congolese Franc", calling_code: "+243", tld: ".cd", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Congo (Republic)", alpha_2: "CG", alpha_3: "COG", numeric: "178", region: "Africa", subregion: "Middle Africa", capital: "Brazzaville", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+242", tld: ".cg", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Costa Rica", alpha_2: "CR", alpha_3: "CRI", numeric: "188", region: "Americas", subregion: "Central America", capital: "San José", currency_code: "CRC", currency_name: "Costa Rican Colón", calling_code: "+506", tld: ".cr", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Côte d'Ivoire", alpha_2: "CI", alpha_3: "CIV", numeric: "384", region: "Africa", subregion: "Western Africa", capital: "Yamoussoukro", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+225", tld: ".ci", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Croatia", alpha_2: "HR", alpha_3: "HRV", numeric: "191", region: "Europe", subregion: "Southern Europe", capital: "Zagreb", currency_code: "EUR", currency_name: "Euro", calling_code: "+385", tld: ".hr", languages: ["Croatian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Cuba", alpha_2: "CU", alpha_3: "CUB", numeric: "192", region: "Americas", subregion: "Caribbean", capital: "Havana", currency_code: "CUP", currency_name: "Cuban Peso", calling_code: "+53", tld: ".cu", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Cyprus", alpha_2: "CY", alpha_3: "CYP", numeric: "196", region: "Europe", subregion: "Southern Europe", capital: "Nicosia", currency_code: "EUR", currency_name: "Euro", calling_code: "+357", tld: ".cy", languages: ["Greek", "Turkish"], eu_member: true, schengen: false, eurozone: true, un_member: true },
  { name: "Czech Republic", alpha_2: "CZ", alpha_3: "CZE", numeric: "203", region: "Europe", subregion: "Eastern Europe", capital: "Prague", currency_code: "CZK", currency_name: "Czech Koruna", calling_code: "+420", tld: ".cz", languages: ["Czech"], eu_member: true, schengen: true, eurozone: false, un_member: true },
  { name: "Denmark", alpha_2: "DK", alpha_3: "DNK", numeric: "208", region: "Europe", subregion: "Northern Europe", capital: "Copenhagen", currency_code: "DKK", currency_name: "Danish Krone", calling_code: "+45", tld: ".dk", languages: ["Danish"], eu_member: true, schengen: true, eurozone: false, un_member: true },
  { name: "Djibouti", alpha_2: "DJ", alpha_3: "DJI", numeric: "262", region: "Africa", subregion: "Eastern Africa", capital: "Djibouti", currency_code: "DJF", currency_name: "Djiboutian Franc", calling_code: "+253", tld: ".dj", languages: ["French", "Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Dominica", alpha_2: "DM", alpha_3: "DMA", numeric: "212", region: "Americas", subregion: "Caribbean", capital: "Roseau", currency_code: "XCD", currency_name: "East Caribbean Dollar", calling_code: "+1-767", tld: ".dm", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Dominican Republic", alpha_2: "DO", alpha_3: "DOM", numeric: "214", region: "Americas", subregion: "Caribbean", capital: "Santo Domingo", currency_code: "DOP", currency_name: "Dominican Peso", calling_code: "+1-809", tld: ".do", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Ecuador", alpha_2: "EC", alpha_3: "ECU", numeric: "218", region: "Americas", subregion: "South America", capital: "Quito", currency_code: "USD", currency_name: "US Dollar", calling_code: "+593", tld: ".ec", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Egypt", alpha_2: "EG", alpha_3: "EGY", numeric: "818", region: "Africa", subregion: "Northern Africa", capital: "Cairo", currency_code: "EGP", currency_name: "Egyptian Pound", calling_code: "+20", tld: ".eg", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "El Salvador", alpha_2: "SV", alpha_3: "SLV", numeric: "222", region: "Americas", subregion: "Central America", capital: "San Salvador", currency_code: "USD", currency_name: "US Dollar", calling_code: "+503", tld: ".sv", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Equatorial Guinea", alpha_2: "GQ", alpha_3: "GNQ", numeric: "226", region: "Africa", subregion: "Middle Africa", capital: "Malabo", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+240", tld: ".gq", languages: ["Spanish", "French", "Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Eritrea", alpha_2: "ER", alpha_3: "ERI", numeric: "232", region: "Africa", subregion: "Eastern Africa", capital: "Asmara", currency_code: "ERN", currency_name: "Eritrean Nakfa", calling_code: "+291", tld: ".er", languages: ["Tigrinya", "Arabic", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Estonia", alpha_2: "EE", alpha_3: "EST", numeric: "233", region: "Europe", subregion: "Northern Europe", capital: "Tallinn", currency_code: "EUR", currency_name: "Euro", calling_code: "+372", tld: ".ee", languages: ["Estonian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Eswatini", alpha_2: "SZ", alpha_3: "SWZ", numeric: "748", region: "Africa", subregion: "Southern Africa", capital: "Mbabane", currency_code: "SZL", currency_name: "Swazi Lilangeni", calling_code: "+268", tld: ".sz", languages: ["Swazi", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Ethiopia", alpha_2: "ET", alpha_3: "ETH", numeric: "231", region: "Africa", subregion: "Eastern Africa", capital: "Addis Ababa", currency_code: "ETB", currency_name: "Ethiopian Birr", calling_code: "+251", tld: ".et", languages: ["Amharic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Fiji", alpha_2: "FJ", alpha_3: "FJI", numeric: "242", region: "Oceania", subregion: "Melanesia", capital: "Suva", currency_code: "FJD", currency_name: "Fijian Dollar", calling_code: "+679", tld: ".fj", languages: ["English", "Fijian", "Hindi"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Finland", alpha_2: "FI", alpha_3: "FIN", numeric: "246", region: "Europe", subregion: "Northern Europe", capital: "Helsinki", currency_code: "EUR", currency_name: "Euro", calling_code: "+358", tld: ".fi", languages: ["Finnish", "Swedish"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "France", alpha_2: "FR", alpha_3: "FRA", numeric: "250", region: "Europe", subregion: "Western Europe", capital: "Paris", currency_code: "EUR", currency_name: "Euro", calling_code: "+33", tld: ".fr", languages: ["French"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Gabon", alpha_2: "GA", alpha_3: "GAB", numeric: "266", region: "Africa", subregion: "Middle Africa", capital: "Libreville", currency_code: "XAF", currency_name: "CFA Franc BEAC", calling_code: "+241", tld: ".ga", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Gambia", alpha_2: "GM", alpha_3: "GMB", numeric: "270", region: "Africa", subregion: "Western Africa", capital: "Banjul", currency_code: "GMD", currency_name: "Gambian Dalasi", calling_code: "+220", tld: ".gm", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Georgia", alpha_2: "GE", alpha_3: "GEO", numeric: "268", region: "Asia", subregion: "Western Asia", capital: "Tbilisi", currency_code: "GEL", currency_name: "Georgian Lari", calling_code: "+995", tld: ".ge", languages: ["Georgian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Germany", alpha_2: "DE", alpha_3: "DEU", numeric: "276", region: "Europe", subregion: "Western Europe", capital: "Berlin", currency_code: "EUR", currency_name: "Euro", calling_code: "+49", tld: ".de", languages: ["German"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Ghana", alpha_2: "GH", alpha_3: "GHA", numeric: "288", region: "Africa", subregion: "Western Africa", capital: "Accra", currency_code: "GHS", currency_name: "Ghanaian Cedi", calling_code: "+233", tld: ".gh", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Greece", alpha_2: "GR", alpha_3: "GRC", numeric: "300", region: "Europe", subregion: "Southern Europe", capital: "Athens", currency_code: "EUR", currency_name: "Euro", calling_code: "+30", tld: ".gr", languages: ["Greek"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Greenland", alpha_2: "GL", alpha_3: "GRL", numeric: "304", region: "Americas", subregion: "Northern America", capital: "Nuuk", currency_code: "DKK", currency_name: "Danish Krone", calling_code: "+299", tld: ".gl", languages: ["Greenlandic"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Guatemala", alpha_2: "GT", alpha_3: "GTM", numeric: "320", region: "Americas", subregion: "Central America", capital: "Guatemala City", currency_code: "GTQ", currency_name: "Guatemalan Quetzal", calling_code: "+502", tld: ".gt", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Guinea", alpha_2: "GN", alpha_3: "GIN", numeric: "324", region: "Africa", subregion: "Western Africa", capital: "Conakry", currency_code: "GNF", currency_name: "Guinean Franc", calling_code: "+224", tld: ".gn", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Guyana", alpha_2: "GY", alpha_3: "GUY", numeric: "328", region: "Americas", subregion: "South America", capital: "Georgetown", currency_code: "GYD", currency_name: "Guyanese Dollar", calling_code: "+592", tld: ".gy", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Haiti", alpha_2: "HT", alpha_3: "HTI", numeric: "332", region: "Americas", subregion: "Caribbean", capital: "Port-au-Prince", currency_code: "HTG", currency_name: "Haitian Gourde", calling_code: "+509", tld: ".ht", languages: ["French", "Haitian Creole"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Honduras", alpha_2: "HN", alpha_3: "HND", numeric: "340", region: "Americas", subregion: "Central America", capital: "Tegucigalpa", currency_code: "HNL", currency_name: "Honduran Lempira", calling_code: "+504", tld: ".hn", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Hong Kong", alpha_2: "HK", alpha_3: "HKG", numeric: "344", region: "Asia", subregion: "Eastern Asia", capital: "Hong Kong", currency_code: "HKD", currency_name: "Hong Kong Dollar", calling_code: "+852", tld: ".hk", languages: ["Chinese", "English"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Hungary", alpha_2: "HU", alpha_3: "HUN", numeric: "348", region: "Europe", subregion: "Eastern Europe", capital: "Budapest", currency_code: "HUF", currency_name: "Hungarian Forint", calling_code: "+36", tld: ".hu", languages: ["Hungarian"], eu_member: true, schengen: true, eurozone: false, un_member: true },
  { name: "Iceland", alpha_2: "IS", alpha_3: "ISL", numeric: "352", region: "Europe", subregion: "Northern Europe", capital: "Reykjavik", currency_code: "ISK", currency_name: "Icelandic Króna", calling_code: "+354", tld: ".is", languages: ["Icelandic"], eu_member: false, schengen: true, eurozone: false, un_member: true },
  { name: "India", alpha_2: "IN", alpha_3: "IND", numeric: "356", region: "Asia", subregion: "Southern Asia", capital: "New Delhi", currency_code: "INR", currency_name: "Indian Rupee", calling_code: "+91", tld: ".in", languages: ["Hindi", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Indonesia", alpha_2: "ID", alpha_3: "IDN", numeric: "360", region: "Asia", subregion: "South-Eastern Asia", capital: "Jakarta", currency_code: "IDR", currency_name: "Indonesian Rupiah", calling_code: "+62", tld: ".id", languages: ["Indonesian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Iran", alpha_2: "IR", alpha_3: "IRN", numeric: "364", region: "Asia", subregion: "Southern Asia", capital: "Tehran", currency_code: "IRR", currency_name: "Iranian Rial", calling_code: "+98", tld: ".ir", languages: ["Persian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Iraq", alpha_2: "IQ", alpha_3: "IRQ", numeric: "368", region: "Asia", subregion: "Western Asia", capital: "Baghdad", currency_code: "IQD", currency_name: "Iraqi Dinar", calling_code: "+964", tld: ".iq", languages: ["Arabic", "Kurdish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Ireland", alpha_2: "IE", alpha_3: "IRL", numeric: "372", region: "Europe", subregion: "Northern Europe", capital: "Dublin", currency_code: "EUR", currency_name: "Euro", calling_code: "+353", tld: ".ie", languages: ["English", "Irish"], eu_member: true, schengen: false, eurozone: true, un_member: true },
  { name: "Israel", alpha_2: "IL", alpha_3: "ISR", numeric: "376", region: "Asia", subregion: "Western Asia", capital: "Jerusalem", currency_code: "ILS", currency_name: "Israeli New Shekel", calling_code: "+972", tld: ".il", languages: ["Hebrew", "Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Italy", alpha_2: "IT", alpha_3: "ITA", numeric: "380", region: "Europe", subregion: "Southern Europe", capital: "Rome", currency_code: "EUR", currency_name: "Euro", calling_code: "+39", tld: ".it", languages: ["Italian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Jamaica", alpha_2: "JM", alpha_3: "JAM", numeric: "388", region: "Americas", subregion: "Caribbean", capital: "Kingston", currency_code: "JMD", currency_name: "Jamaican Dollar", calling_code: "+1-876", tld: ".jm", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Japan", alpha_2: "JP", alpha_3: "JPN", numeric: "392", region: "Asia", subregion: "Eastern Asia", capital: "Tokyo", currency_code: "JPY", currency_name: "Japanese Yen", calling_code: "+81", tld: ".jp", languages: ["Japanese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Jordan", alpha_2: "JO", alpha_3: "JOR", numeric: "400", region: "Asia", subregion: "Western Asia", capital: "Amman", currency_code: "JOD", currency_name: "Jordanian Dinar", calling_code: "+962", tld: ".jo", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Kazakhstan", alpha_2: "KZ", alpha_3: "KAZ", numeric: "398", region: "Asia", subregion: "Central Asia", capital: "Astana", currency_code: "KZT", currency_name: "Kazakhstani Tenge", calling_code: "+7", tld: ".kz", languages: ["Kazakh", "Russian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Kenya", alpha_2: "KE", alpha_3: "KEN", numeric: "404", region: "Africa", subregion: "Eastern Africa", capital: "Nairobi", currency_code: "KES", currency_name: "Kenyan Shilling", calling_code: "+254", tld: ".ke", languages: ["English", "Swahili"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Kiribati", alpha_2: "KI", alpha_3: "KIR", numeric: "296", region: "Oceania", subregion: "Micronesia", capital: "Tarawa", currency_code: "AUD", currency_name: "Australian Dollar", calling_code: "+686", tld: ".ki", languages: ["English", "Gilbertese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Kuwait", alpha_2: "KW", alpha_3: "KWT", numeric: "414", region: "Asia", subregion: "Western Asia", capital: "Kuwait City", currency_code: "KWD", currency_name: "Kuwaiti Dinar", calling_code: "+965", tld: ".kw", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Kyrgyzstan", alpha_2: "KG", alpha_3: "KGZ", numeric: "417", region: "Asia", subregion: "Central Asia", capital: "Bishkek", currency_code: "KGS", currency_name: "Kyrgyz Som", calling_code: "+996", tld: ".kg", languages: ["Kyrgyz", "Russian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Laos", alpha_2: "LA", alpha_3: "LAO", numeric: "418", region: "Asia", subregion: "South-Eastern Asia", capital: "Vientiane", currency_code: "LAK", currency_name: "Lao Kip", calling_code: "+856", tld: ".la", languages: ["Lao"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Latvia", alpha_2: "LV", alpha_3: "LVA", numeric: "428", region: "Europe", subregion: "Northern Europe", capital: "Riga", currency_code: "EUR", currency_name: "Euro", calling_code: "+371", tld: ".lv", languages: ["Latvian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Lebanon", alpha_2: "LB", alpha_3: "LBN", numeric: "422", region: "Asia", subregion: "Western Asia", capital: "Beirut", currency_code: "LBP", currency_name: "Lebanese Pound", calling_code: "+961", tld: ".lb", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Lesotho", alpha_2: "LS", alpha_3: "LSO", numeric: "426", region: "Africa", subregion: "Southern Africa", capital: "Maseru", currency_code: "LSL", currency_name: "Lesotho Loti", calling_code: "+266", tld: ".ls", languages: ["Sesotho", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Liberia", alpha_2: "LR", alpha_3: "LBR", numeric: "430", region: "Africa", subregion: "Western Africa", capital: "Monrovia", currency_code: "LRD", currency_name: "Liberian Dollar", calling_code: "+231", tld: ".lr", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Libya", alpha_2: "LY", alpha_3: "LBY", numeric: "434", region: "Africa", subregion: "Northern Africa", capital: "Tripoli", currency_code: "LYD", currency_name: "Libyan Dinar", calling_code: "+218", tld: ".ly", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Liechtenstein", alpha_2: "LI", alpha_3: "LIE", numeric: "438", region: "Europe", subregion: "Western Europe", capital: "Vaduz", currency_code: "CHF", currency_name: "Swiss Franc", calling_code: "+423", tld: ".li", languages: ["German"], eu_member: false, schengen: true, eurozone: false, un_member: true },
  { name: "Lithuania", alpha_2: "LT", alpha_3: "LTU", numeric: "440", region: "Europe", subregion: "Northern Europe", capital: "Vilnius", currency_code: "EUR", currency_name: "Euro", calling_code: "+370", tld: ".lt", languages: ["Lithuanian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Luxembourg", alpha_2: "LU", alpha_3: "LUX", numeric: "442", region: "Europe", subregion: "Western Europe", capital: "Luxembourg", currency_code: "EUR", currency_name: "Euro", calling_code: "+352", tld: ".lu", languages: ["Luxembourgish", "French", "German"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Macau", alpha_2: "MO", alpha_3: "MAC", numeric: "446", region: "Asia", subregion: "Eastern Asia", capital: "Macau", currency_code: "MOP", currency_name: "Macanese Pataca", calling_code: "+853", tld: ".mo", languages: ["Chinese", "Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Madagascar", alpha_2: "MG", alpha_3: "MDG", numeric: "450", region: "Africa", subregion: "Eastern Africa", capital: "Antananarivo", currency_code: "MGA", currency_name: "Malagasy Ariary", calling_code: "+261", tld: ".mg", languages: ["Malagasy", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Malawi", alpha_2: "MW", alpha_3: "MWI", numeric: "454", region: "Africa", subregion: "Eastern Africa", capital: "Lilongwe", currency_code: "MWK", currency_name: "Malawian Kwacha", calling_code: "+265", tld: ".mw", languages: ["English", "Chichewa"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Malaysia", alpha_2: "MY", alpha_3: "MYS", numeric: "458", region: "Asia", subregion: "South-Eastern Asia", capital: "Kuala Lumpur", currency_code: "MYR", currency_name: "Malaysian Ringgit", calling_code: "+60", tld: ".my", languages: ["Malay"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Maldives", alpha_2: "MV", alpha_3: "MDV", numeric: "462", region: "Asia", subregion: "Southern Asia", capital: "Malé", currency_code: "MVR", currency_name: "Maldivian Rufiyaa", calling_code: "+960", tld: ".mv", languages: ["Dhivehi"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Mali", alpha_2: "ML", alpha_3: "MLI", numeric: "466", region: "Africa", subregion: "Western Africa", capital: "Bamako", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+223", tld: ".ml", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Malta", alpha_2: "MT", alpha_3: "MLT", numeric: "470", region: "Europe", subregion: "Southern Europe", capital: "Valletta", currency_code: "EUR", currency_name: "Euro", calling_code: "+356", tld: ".mt", languages: ["Maltese", "English"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Mauritania", alpha_2: "MR", alpha_3: "MRT", numeric: "478", region: "Africa", subregion: "Western Africa", capital: "Nouakchott", currency_code: "MRU", currency_name: "Mauritanian Ouguiya", calling_code: "+222", tld: ".mr", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Mauritius", alpha_2: "MU", alpha_3: "MUS", numeric: "480", region: "Africa", subregion: "Eastern Africa", capital: "Port Louis", currency_code: "MUR", currency_name: "Mauritian Rupee", calling_code: "+230", tld: ".mu", languages: ["English", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Mexico", alpha_2: "MX", alpha_3: "MEX", numeric: "484", region: "Americas", subregion: "Central America", capital: "Mexico City", currency_code: "MXN", currency_name: "Mexican Peso", calling_code: "+52", tld: ".mx", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Moldova", alpha_2: "MD", alpha_3: "MDA", numeric: "498", region: "Europe", subregion: "Eastern Europe", capital: "Chișinău", currency_code: "MDL", currency_name: "Moldovan Leu", calling_code: "+373", tld: ".md", languages: ["Romanian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Monaco", alpha_2: "MC", alpha_3: "MCO", numeric: "492", region: "Europe", subregion: "Western Europe", capital: "Monaco", currency_code: "EUR", currency_name: "Euro", calling_code: "+377", tld: ".mc", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Mongolia", alpha_2: "MN", alpha_3: "MNG", numeric: "496", region: "Asia", subregion: "Eastern Asia", capital: "Ulaanbaatar", currency_code: "MNT", currency_name: "Mongolian Tögrög", calling_code: "+976", tld: ".mn", languages: ["Mongolian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Montenegro", alpha_2: "ME", alpha_3: "MNE", numeric: "499", region: "Europe", subregion: "Southern Europe", capital: "Podgorica", currency_code: "EUR", currency_name: "Euro", calling_code: "+382", tld: ".me", languages: ["Montenegrin"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Morocco", alpha_2: "MA", alpha_3: "MAR", numeric: "504", region: "Africa", subregion: "Northern Africa", capital: "Rabat", currency_code: "MAD", currency_name: "Moroccan Dirham", calling_code: "+212", tld: ".ma", languages: ["Arabic", "Berber"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Mozambique", alpha_2: "MZ", alpha_3: "MOZ", numeric: "508", region: "Africa", subregion: "Eastern Africa", capital: "Maputo", currency_code: "MZN", currency_name: "Mozambican Metical", calling_code: "+258", tld: ".mz", languages: ["Portuguese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Myanmar", alpha_2: "MM", alpha_3: "MMR", numeric: "104", region: "Asia", subregion: "South-Eastern Asia", capital: "Naypyidaw", currency_code: "MMK", currency_name: "Myanmar Kyat", calling_code: "+95", tld: ".mm", languages: ["Burmese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Namibia", alpha_2: "NA", alpha_3: "NAM", numeric: "516", region: "Africa", subregion: "Southern Africa", capital: "Windhoek", currency_code: "NAD", currency_name: "Namibian Dollar", calling_code: "+264", tld: ".na", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Nepal", alpha_2: "NP", alpha_3: "NPL", numeric: "524", region: "Asia", subregion: "Southern Asia", capital: "Kathmandu", currency_code: "NPR", currency_name: "Nepalese Rupee", calling_code: "+977", tld: ".np", languages: ["Nepali"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Netherlands", alpha_2: "NL", alpha_3: "NLD", numeric: "528", region: "Europe", subregion: "Western Europe", capital: "Amsterdam", currency_code: "EUR", currency_name: "Euro", calling_code: "+31", tld: ".nl", languages: ["Dutch"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "New Zealand", alpha_2: "NZ", alpha_3: "NZL", numeric: "554", region: "Oceania", subregion: "Australia and New Zealand", capital: "Wellington", currency_code: "NZD", currency_name: "New Zealand Dollar", calling_code: "+64", tld: ".nz", languages: ["English", "Maori"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Nicaragua", alpha_2: "NI", alpha_3: "NIC", numeric: "558", region: "Americas", subregion: "Central America", capital: "Managua", currency_code: "NIO", currency_name: "Nicaraguan Córdoba", calling_code: "+505", tld: ".ni", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Niger", alpha_2: "NE", alpha_3: "NER", numeric: "562", region: "Africa", subregion: "Western Africa", capital: "Niamey", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+227", tld: ".ne", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Nigeria", alpha_2: "NG", alpha_3: "NGA", numeric: "566", region: "Africa", subregion: "Western Africa", capital: "Abuja", currency_code: "NGN", currency_name: "Nigerian Naira", calling_code: "+234", tld: ".ng", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "North Korea", alpha_2: "KP", alpha_3: "PRK", numeric: "408", region: "Asia", subregion: "Eastern Asia", capital: "Pyongyang", currency_code: "KPW", currency_name: "North Korean Won", calling_code: "+850", tld: ".kp", languages: ["Korean"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "North Macedonia", alpha_2: "MK", alpha_3: "MKD", numeric: "807", region: "Europe", subregion: "Southern Europe", capital: "Skopje", currency_code: "MKD", currency_name: "Macedonian Denar", calling_code: "+389", tld: ".mk", languages: ["Macedonian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Norway", alpha_2: "NO", alpha_3: "NOR", numeric: "578", region: "Europe", subregion: "Northern Europe", capital: "Oslo", currency_code: "NOK", currency_name: "Norwegian Krone", calling_code: "+47", tld: ".no", languages: ["Norwegian"], eu_member: false, schengen: true, eurozone: false, un_member: true },
  { name: "Oman", alpha_2: "OM", alpha_3: "OMN", numeric: "512", region: "Asia", subregion: "Western Asia", capital: "Muscat", currency_code: "OMR", currency_name: "Omani Rial", calling_code: "+968", tld: ".om", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Pakistan", alpha_2: "PK", alpha_3: "PAK", numeric: "586", region: "Asia", subregion: "Southern Asia", capital: "Islamabad", currency_code: "PKR", currency_name: "Pakistani Rupee", calling_code: "+92", tld: ".pk", languages: ["Urdu", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Panama", alpha_2: "PA", alpha_3: "PAN", numeric: "591", region: "Americas", subregion: "Central America", capital: "Panama City", currency_code: "PAB", currency_name: "Panamanian Balboa", calling_code: "+507", tld: ".pa", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Papua New Guinea", alpha_2: "PG", alpha_3: "PNG", numeric: "598", region: "Oceania", subregion: "Melanesia", capital: "Port Moresby", currency_code: "PGK", currency_name: "Papua New Guinean Kina", calling_code: "+675", tld: ".pg", languages: ["English", "Tok Pisin", "Hiri Motu"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Paraguay", alpha_2: "PY", alpha_3: "PRY", numeric: "600", region: "Americas", subregion: "South America", capital: "Asunción", currency_code: "PYG", currency_name: "Paraguayan Guaraní", calling_code: "+595", tld: ".py", languages: ["Spanish", "Guaraní"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Peru", alpha_2: "PE", alpha_3: "PER", numeric: "604", region: "Americas", subregion: "South America", capital: "Lima", currency_code: "PEN", currency_name: "Peruvian Sol", calling_code: "+51", tld: ".pe", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Philippines", alpha_2: "PH", alpha_3: "PHL", numeric: "608", region: "Asia", subregion: "South-Eastern Asia", capital: "Manila", currency_code: "PHP", currency_name: "Philippine Peso", calling_code: "+63", tld: ".ph", languages: ["Filipino", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Poland", alpha_2: "PL", alpha_3: "POL", numeric: "616", region: "Europe", subregion: "Eastern Europe", capital: "Warsaw", currency_code: "PLN", currency_name: "Polish Złoty", calling_code: "+48", tld: ".pl", languages: ["Polish"], eu_member: true, schengen: true, eurozone: false, un_member: true },
  { name: "Portugal", alpha_2: "PT", alpha_3: "PRT", numeric: "620", region: "Europe", subregion: "Southern Europe", capital: "Lisbon", currency_code: "EUR", currency_name: "Euro", calling_code: "+351", tld: ".pt", languages: ["Portuguese"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Qatar", alpha_2: "QA", alpha_3: "QAT", numeric: "634", region: "Asia", subregion: "Western Asia", capital: "Doha", currency_code: "QAR", currency_name: "Qatari Riyal", calling_code: "+974", tld: ".qa", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Romania", alpha_2: "RO", alpha_3: "ROU", numeric: "642", region: "Europe", subregion: "Eastern Europe", capital: "Bucharest", currency_code: "RON", currency_name: "Romanian Leu", calling_code: "+40", tld: ".ro", languages: ["Romanian"], eu_member: true, schengen: false, eurozone: false, un_member: true },
  { name: "Russia", alpha_2: "RU", alpha_3: "RUS", numeric: "643", region: "Europe", subregion: "Eastern Europe", capital: "Moscow", currency_code: "RUB", currency_name: "Russian Ruble", calling_code: "+7", tld: ".ru", languages: ["Russian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Rwanda", alpha_2: "RW", alpha_3: "RWA", numeric: "646", region: "Africa", subregion: "Eastern Africa", capital: "Kigali", currency_code: "RWF", currency_name: "Rwandan Franc", calling_code: "+250", tld: ".rw", languages: ["Kinyarwanda", "French", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Saudi Arabia", alpha_2: "SA", alpha_3: "SAU", numeric: "682", region: "Asia", subregion: "Western Asia", capital: "Riyadh", currency_code: "SAR", currency_name: "Saudi Riyal", calling_code: "+966", tld: ".sa", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Senegal", alpha_2: "SN", alpha_3: "SEN", numeric: "686", region: "Africa", subregion: "Western Africa", capital: "Dakar", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+221", tld: ".sn", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Serbia", alpha_2: "RS", alpha_3: "SRB", numeric: "688", region: "Europe", subregion: "Southern Europe", capital: "Belgrade", currency_code: "RSD", currency_name: "Serbian Dinar", calling_code: "+381", tld: ".rs", languages: ["Serbian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Singapore", alpha_2: "SG", alpha_3: "SGP", numeric: "702", region: "Asia", subregion: "South-Eastern Asia", capital: "Singapore", currency_code: "SGD", currency_name: "Singapore Dollar", calling_code: "+65", tld: ".sg", languages: ["English", "Malay", "Mandarin", "Tamil"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Slovakia", alpha_2: "SK", alpha_3: "SVK", numeric: "703", region: "Europe", subregion: "Eastern Europe", capital: "Bratislava", currency_code: "EUR", currency_name: "Euro", calling_code: "+421", tld: ".sk", languages: ["Slovak"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Slovenia", alpha_2: "SI", alpha_3: "SVN", numeric: "705", region: "Europe", subregion: "Southern Europe", capital: "Ljubljana", currency_code: "EUR", currency_name: "Euro", calling_code: "+386", tld: ".si", languages: ["Slovenian"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Somalia", alpha_2: "SO", alpha_3: "SOM", numeric: "706", region: "Africa", subregion: "Eastern Africa", capital: "Mogadishu", currency_code: "SOS", currency_name: "Somali Shilling", calling_code: "+252", tld: ".so", languages: ["Somali", "Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "South Africa", alpha_2: "ZA", alpha_3: "ZAF", numeric: "710", region: "Africa", subregion: "Southern Africa", capital: "Pretoria", currency_code: "ZAR", currency_name: "South African Rand", calling_code: "+27", tld: ".za", languages: ["Afrikaans", "English", "Zulu", "Xhosa"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "South Korea", alpha_2: "KR", alpha_3: "KOR", numeric: "410", region: "Asia", subregion: "Eastern Asia", capital: "Seoul", currency_code: "KRW", currency_name: "South Korean Won", calling_code: "+82", tld: ".kr", languages: ["Korean"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "South Sudan", alpha_2: "SS", alpha_3: "SSD", numeric: "728", region: "Africa", subregion: "Eastern Africa", capital: "Juba", currency_code: "SSP", currency_name: "South Sudanese Pound", calling_code: "+211", tld: ".ss", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Spain", alpha_2: "ES", alpha_3: "ESP", numeric: "724", region: "Europe", subregion: "Southern Europe", capital: "Madrid", currency_code: "EUR", currency_name: "Euro", calling_code: "+34", tld: ".es", languages: ["Spanish"], eu_member: true, schengen: true, eurozone: true, un_member: true },
  { name: "Sri Lanka", alpha_2: "LK", alpha_3: "LKA", numeric: "144", region: "Asia", subregion: "Southern Asia", capital: "Sri Jayawardenepura Kotte", currency_code: "LKR", currency_name: "Sri Lankan Rupee", calling_code: "+94", tld: ".lk", languages: ["Sinhala", "Tamil"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Sudan", alpha_2: "SD", alpha_3: "SDN", numeric: "729", region: "Africa", subregion: "Northern Africa", capital: "Khartoum", currency_code: "SDG", currency_name: "Sudanese Pound", calling_code: "+249", tld: ".sd", languages: ["Arabic", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Suriname", alpha_2: "SR", alpha_3: "SUR", numeric: "740", region: "Americas", subregion: "South America", capital: "Paramaribo", currency_code: "SRD", currency_name: "Surinamese Dollar", calling_code: "+597", tld: ".sr", languages: ["Dutch"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Sweden", alpha_2: "SE", alpha_3: "SWE", numeric: "752", region: "Europe", subregion: "Northern Europe", capital: "Stockholm", currency_code: "SEK", currency_name: "Swedish Krona", calling_code: "+46", tld: ".se", languages: ["Swedish"], eu_member: true, schengen: true, eurozone: false, un_member: true },
  { name: "Switzerland", alpha_2: "CH", alpha_3: "CHE", numeric: "756", region: "Europe", subregion: "Western Europe", capital: "Bern", currency_code: "CHF", currency_name: "Swiss Franc", calling_code: "+41", tld: ".ch", languages: ["German", "French", "Italian", "Romansh"], eu_member: false, schengen: true, eurozone: false, un_member: true },
  { name: "Syria", alpha_2: "SY", alpha_3: "SYR", numeric: "760", region: "Asia", subregion: "Western Asia", capital: "Damascus", currency_code: "SYP", currency_name: "Syrian Pound", calling_code: "+963", tld: ".sy", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Taiwan", alpha_2: "TW", alpha_3: "TWN", numeric: "158", region: "Asia", subregion: "Eastern Asia", capital: "Taipei", currency_code: "TWD", currency_name: "New Taiwan Dollar", calling_code: "+886", tld: ".tw", languages: ["Mandarin Chinese"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Tajikistan", alpha_2: "TJ", alpha_3: "TJK", numeric: "762", region: "Asia", subregion: "Central Asia", capital: "Dushanbe", currency_code: "TJS", currency_name: "Tajikistani Somoni", calling_code: "+992", tld: ".tj", languages: ["Tajik"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Tanzania", alpha_2: "TZ", alpha_3: "TZA", numeric: "834", region: "Africa", subregion: "Eastern Africa", capital: "Dodoma", currency_code: "TZS", currency_name: "Tanzanian Shilling", calling_code: "+255", tld: ".tz", languages: ["Swahili", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Thailand", alpha_2: "TH", alpha_3: "THA", numeric: "764", region: "Asia", subregion: "South-Eastern Asia", capital: "Bangkok", currency_code: "THB", currency_name: "Thai Baht", calling_code: "+66", tld: ".th", languages: ["Thai"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Togo", alpha_2: "TG", alpha_3: "TGO", numeric: "768", region: "Africa", subregion: "Western Africa", capital: "Lomé", currency_code: "XOF", currency_name: "CFA Franc BCEAO", calling_code: "+228", tld: ".tg", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Trinidad and Tobago", alpha_2: "TT", alpha_3: "TTO", numeric: "780", region: "Americas", subregion: "Caribbean", capital: "Port of Spain", currency_code: "TTD", currency_name: "Trinidad and Tobago Dollar", calling_code: "+1-868", tld: ".tt", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Tunisia", alpha_2: "TN", alpha_3: "TUN", numeric: "788", region: "Africa", subregion: "Northern Africa", capital: "Tunis", currency_code: "TND", currency_name: "Tunisian Dinar", calling_code: "+216", tld: ".tn", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Turkey", alpha_2: "TR", alpha_3: "TUR", numeric: "792", region: "Asia", subregion: "Western Asia", capital: "Ankara", currency_code: "TRY", currency_name: "Turkish Lira", calling_code: "+90", tld: ".tr", languages: ["Turkish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Turkmenistan", alpha_2: "TM", alpha_3: "TKM", numeric: "795", region: "Asia", subregion: "Central Asia", capital: "Ashgabat", currency_code: "TMT", currency_name: "Turkmenistani Manat", calling_code: "+993", tld: ".tm", languages: ["Turkmen"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Uganda", alpha_2: "UG", alpha_3: "UGA", numeric: "800", region: "Africa", subregion: "Eastern Africa", capital: "Kampala", currency_code: "UGX", currency_name: "Ugandan Shilling", calling_code: "+256", tld: ".ug", languages: ["English", "Swahili"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Ukraine", alpha_2: "UA", alpha_3: "UKR", numeric: "804", region: "Europe", subregion: "Eastern Europe", capital: "Kyiv", currency_code: "UAH", currency_name: "Ukrainian Hryvnia", calling_code: "+380", tld: ".ua", languages: ["Ukrainian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "United Arab Emirates", alpha_2: "AE", alpha_3: "ARE", numeric: "784", region: "Asia", subregion: "Western Asia", capital: "Abu Dhabi", currency_code: "AED", currency_name: "UAE Dirham", calling_code: "+971", tld: ".ae", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "United Kingdom", alpha_2: "GB", alpha_3: "GBR", numeric: "826", region: "Europe", subregion: "Northern Europe", capital: "London", currency_code: "GBP", currency_name: "British Pound", calling_code: "+44", tld: ".uk", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "United States", alpha_2: "US", alpha_3: "USA", numeric: "840", region: "Americas", subregion: "Northern America", capital: "Washington, D.C.", currency_code: "USD", currency_name: "US Dollar", calling_code: "+1", tld: ".us", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Uruguay", alpha_2: "UY", alpha_3: "URY", numeric: "858", region: "Americas", subregion: "South America", capital: "Montevideo", currency_code: "UYU", currency_name: "Uruguayan Peso", calling_code: "+598", tld: ".uy", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Uzbekistan", alpha_2: "UZ", alpha_3: "UZB", numeric: "860", region: "Asia", subregion: "Central Asia", capital: "Tashkent", currency_code: "UZS", currency_name: "Uzbekistani Som", calling_code: "+998", tld: ".uz", languages: ["Uzbek"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Vanuatu", alpha_2: "VU", alpha_3: "VUT", numeric: "548", region: "Oceania", subregion: "Melanesia", capital: "Port Vila", currency_code: "VUV", currency_name: "Vanuatu Vatu", calling_code: "+678", tld: ".vu", languages: ["Bislama", "English", "French"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Vatican City", alpha_2: "VA", alpha_3: "VAT", numeric: "336", region: "Europe", subregion: "Southern Europe", capital: "Vatican City", currency_code: "EUR", currency_name: "Euro", calling_code: "+379", tld: ".va", languages: ["Italian", "Latin"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Venezuela", alpha_2: "VE", alpha_3: "VEN", numeric: "862", region: "Americas", subregion: "South America", capital: "Caracas", currency_code: "VES", currency_name: "Venezuelan Bolívar", calling_code: "+58", tld: ".ve", languages: ["Spanish"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Vietnam", alpha_2: "VN", alpha_3: "VNM", numeric: "704", region: "Asia", subregion: "South-Eastern Asia", capital: "Hanoi", currency_code: "VND", currency_name: "Vietnamese Đồng", calling_code: "+84", tld: ".vn", languages: ["Vietnamese"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Yemen", alpha_2: "YE", alpha_3: "YEM", numeric: "887", region: "Asia", subregion: "Western Asia", capital: "Sana'a", currency_code: "YER", currency_name: "Yemeni Rial", calling_code: "+967", tld: ".ye", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Zambia", alpha_2: "ZM", alpha_3: "ZMB", numeric: "894", region: "Africa", subregion: "Eastern Africa", capital: "Lusaka", currency_code: "ZMW", currency_name: "Zambian Kwacha", calling_code: "+260", tld: ".zm", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Zimbabwe", alpha_2: "ZW", alpha_3: "ZWE", numeric: "716", region: "Africa", subregion: "Eastern Africa", capital: "Harare", currency_code: "ZWL", currency_name: "Zimbabwean Dollar", calling_code: "+263", tld: ".zw", languages: ["English", "Shona", "Ndebele"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  // Additional territories
  { name: "Puerto Rico", alpha_2: "PR", alpha_3: "PRI", numeric: "630", region: "Americas", subregion: "Caribbean", capital: "San Juan", currency_code: "USD", currency_name: "US Dollar", calling_code: "+1-787", tld: ".pr", languages: ["Spanish", "English"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Guam", alpha_2: "GU", alpha_3: "GUM", numeric: "316", region: "Oceania", subregion: "Micronesia", capital: "Hagåtña", currency_code: "USD", currency_name: "US Dollar", calling_code: "+1-671", tld: ".gu", languages: ["English", "Chamorro"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Curaçao", alpha_2: "CW", alpha_3: "CUW", numeric: "531", region: "Americas", subregion: "Caribbean", capital: "Willemstad", currency_code: "ANG", currency_name: "Netherlands Antillean Guilder", calling_code: "+599", tld: ".cw", languages: ["Dutch", "Papiamentu"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Faroe Islands", alpha_2: "FO", alpha_3: "FRO", numeric: "234", region: "Europe", subregion: "Northern Europe", capital: "Tórshavn", currency_code: "DKK", currency_name: "Danish Krone", calling_code: "+298", tld: ".fo", languages: ["Faroese", "Danish"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Gibraltar", alpha_2: "GI", alpha_3: "GIB", numeric: "292", region: "Europe", subregion: "Southern Europe", capital: "Gibraltar", currency_code: "GIP", currency_name: "Gibraltar Pound", calling_code: "+350", tld: ".gi", languages: ["English"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Kosovo", alpha_2: "XK", alpha_3: "XKX", numeric: "383", region: "Europe", subregion: "Southern Europe", capital: "Pristina", currency_code: "EUR", currency_name: "Euro", calling_code: "+383", tld: ".xk", languages: ["Albanian", "Serbian"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Palestine", alpha_2: "PS", alpha_3: "PSE", numeric: "275", region: "Asia", subregion: "Western Asia", capital: "Ramallah", currency_code: "ILS", currency_name: "Israeli New Shekel", calling_code: "+970", tld: ".ps", languages: ["Arabic"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Réunion", alpha_2: "RE", alpha_3: "REU", numeric: "638", region: "Africa", subregion: "Eastern Africa", capital: "Saint-Denis", currency_code: "EUR", currency_name: "Euro", calling_code: "+262", tld: ".re", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Martinique", alpha_2: "MQ", alpha_3: "MTQ", numeric: "474", region: "Americas", subregion: "Caribbean", capital: "Fort-de-France", currency_code: "EUR", currency_name: "Euro", calling_code: "+596", tld: ".mq", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Guadeloupe", alpha_2: "GP", alpha_3: "GLP", numeric: "312", region: "Americas", subregion: "Caribbean", capital: "Basse-Terre", currency_code: "EUR", currency_name: "Euro", calling_code: "+590", tld: ".gp", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "French Guiana", alpha_2: "GF", alpha_3: "GUF", numeric: "254", region: "Americas", subregion: "South America", capital: "Cayenne", currency_code: "EUR", currency_name: "Euro", calling_code: "+594", tld: ".gf", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Mayotte", alpha_2: "YT", alpha_3: "MYT", numeric: "175", region: "Africa", subregion: "Eastern Africa", capital: "Mamoudzou", currency_code: "EUR", currency_name: "Euro", calling_code: "+262", tld: ".yt", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "New Caledonia", alpha_2: "NC", alpha_3: "NCL", numeric: "540", region: "Oceania", subregion: "Melanesia", capital: "Nouméa", currency_code: "XPF", currency_name: "CFP Franc", calling_code: "+687", tld: ".nc", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "French Polynesia", alpha_2: "PF", alpha_3: "PYF", numeric: "258", region: "Oceania", subregion: "Polynesia", capital: "Papeete", currency_code: "XPF", currency_name: "CFP Franc", calling_code: "+689", tld: ".pf", languages: ["French"], eu_member: false, schengen: false, eurozone: false, un_member: false },
  { name: "Samoa", alpha_2: "WS", alpha_3: "WSM", numeric: "882", region: "Oceania", subregion: "Polynesia", capital: "Apia", currency_code: "WST", currency_name: "Samoan Tālā", calling_code: "+685", tld: ".ws", languages: ["Samoan", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Tonga", alpha_2: "TO", alpha_3: "TON", numeric: "776", region: "Oceania", subregion: "Polynesia", capital: "Nukuʻalofa", currency_code: "TOP", currency_name: "Tongan Paʻanga", calling_code: "+676", tld: ".to", languages: ["Tongan", "English"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Timor-Leste", alpha_2: "TL", alpha_3: "TLS", numeric: "626", region: "Asia", subregion: "South-Eastern Asia", capital: "Dili", currency_code: "USD", currency_name: "US Dollar", calling_code: "+670", tld: ".tl", languages: ["Portuguese", "Tetum"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "Seychelles", alpha_2: "SC", alpha_3: "SYC", numeric: "690", region: "Africa", subregion: "Eastern Africa", capital: "Victoria", currency_code: "SCR", currency_name: "Seychellois Rupee", calling_code: "+248", tld: ".sc", languages: ["French", "English", "Seychellois Creole"], eu_member: false, schengen: false, eurozone: false, un_member: true },
  { name: "San Marino", alpha_2: "SM", alpha_3: "SMR", numeric: "674", region: "Europe", subregion: "Southern Europe", capital: "San Marino", currency_code: "EUR", currency_name: "Euro", calling_code: "+378", tld: ".sm", languages: ["Italian"], eu_member: false, schengen: false, eurozone: false, un_member: true },
];

// Build lookup indices
const alpha2Index = new Map<string, CountryEntry>();
const alpha3Index = new Map<string, CountryEntry>();
const numericIndex = new Map<string, CountryEntry>();
for (const c of COUNTRIES) {
  alpha2Index.set(c.alpha_2, c);
  alpha3Index.set(c.alpha_3, c);
  numericIndex.set(c.numeric, c);
}

function searchCountries(query: string): CountryEntry[] {
  const q = query.trim().toUpperCase();

  // 1. Exact alpha-2 match
  const a2 = alpha2Index.get(q);
  if (a2) return [a2];

  // 2. Exact alpha-3 match
  const a3 = alpha3Index.get(q);
  if (a3) return [a3];

  // 3. Exact numeric match
  const num = numericIndex.get(q.padStart(3, "0"));
  if (num) return [num];

  // 4. Name search (case insensitive)
  const lowerQ = query.trim().toLowerCase();
  const nameMatches = COUNTRIES.filter((c) =>
    c.name.toLowerCase().includes(lowerQ) ||
    c.capital.toLowerCase().includes(lowerQ),
  );
  return nameMatches;
}

registerCapability("iso-country-lookup", async (input: CapabilityInput) => {
  const raw = (
    (input.query as string) ??
    (input.country as string) ??
    (input.code as string) ??
    (input.task as string) ??
    ""
  ).trim();
  if (!raw) {
    throw new Error(
      "'query' or 'country' is required. Provide a country name, alpha-2/alpha-3 code, or numeric code.",
    );
  }

  const matches = searchCountries(raw);

  if (matches.length === 1) {
    return {
      output: {
        query: raw,
        match: matches[0],
      },
      provenance: {
        source: "algorithmic",
        fetched_at: new Date().toISOString(),
      },
    };
  }

  return {
    output: {
      query: raw,
      matches,
      total_matches: matches.length,
      ...(matches.length === 0
        ? { error: `No country found matching "${raw}".` }
        : {}),
    },
    provenance: {
      source: "algorithmic",
      fetched_at: new Date().toISOString(),
    },
  };
});
