-- Migration: Dual-profile SQS architecture
-- Adds capability_type classification, fallback metadata, and computed SQS score columns

-- 1. Add new columns to capabilities table
ALTER TABLE capabilities ADD COLUMN capability_type TEXT NOT NULL DEFAULT 'stable_api';
ALTER TABLE capabilities ADD COLUMN fallback_capability_slug TEXT;
ALTER TABLE capabilities ADD COLUMN fallback_coverage TEXT;
ALTER TABLE capabilities ADD COLUMN fallback_verification_level TEXT;
ALTER TABLE capabilities ADD COLUMN error_codes_json JSONB;
ALTER TABLE capabilities ADD COLUMN qp_score NUMERIC(5,2);
ALTER TABLE capabilities ADD COLUMN rp_score NUMERIC(5,2);
ALTER TABLE capabilities ADD COLUMN matrix_sqs NUMERIC(5,2);

-- 2. Classify all capabilities by type

-- deterministic: pure computation, no external calls
UPDATE capabilities SET capability_type = 'deterministic' WHERE slug IN (
  'bank-bic-lookup',
  'company-id-detect',
  'country-tax-rates',
  'cron-explain',
  'csv-clean',
  'csv-to-json',
  'dangerous-goods-classify',
  'data-protection-authority-lookup',
  'data-quality-check',
  'date-parse',
  'deduplicate',
  'diff-json',
  'employment-cost-estimate',
  'eu-ai-act-classify',
  'financial-year-dates',
  'flatten-json',
  'gitignore-generate',
  'http-to-curl',
  'iban-validate',
  'incoterms-explain',
  'invoice-validate',
  'isbn-validate',
  'iso-country-lookup',
  'json-repair',
  'json-schema-validate',
  'json-to-csv',
  'json-to-pydantic',
  'json-to-typescript',
  'json-to-zod',
  'jwt-decode',
  'llm-cost-calculate',
  'llm-output-validate',
  'log-parse',
  'markdown-to-html',
  'marketplace-fee-calculate',
  'name-parse',
  'openapi-validate',
  'password-strength',
  'payment-reference-generate',
  'phone-normalize',
  'schema-infer',
  'sepa-xml-validate',
  'shipping-cost-estimate',
  'shipping-track',
  'skill-extract',
  'skill-gap-analyze',
  'swift-message-parse',
  'swift-validate',
  'timezone-meeting-find',
  'tool-call-validate',
  'unit-convert',
  'vat-format-validate',
  'vat-rate-lookup',
  'work-permit-requirements',
  'xml-to-json'
);

-- scraping: uses Browserless.io for web scraping
UPDATE capabilities SET capability_type = 'scraping' WHERE slug IN (
  'accessibility-audit',
  'amazon-price',
  'australian-company-data',
  'austrian-company-data',
  'belgian-company-data',
  'business-license-check-se',
  'canadian-company-data',
  'company-tech-stack',
  'competitor-compare',
  'container-track',
  'cookie-scan',
  'credit-report-summary',
  'customs-duty-lookup',
  'dutch-company-data',
  'employer-review-summary',
  'eu-court-case-search',
  'eu-regulation-search',
  'eu-trademark-search',
  'gdpr-fine-lookup',
  'german-company-data',
  'hong-kong-company-data',
  'html-to-pdf',
  'indian-company-data',
  'irish-company-data',
  'italian-company-data',
  'japanese-company-data',
  'landing-page-roast',
  'latvian-company-data',
  'lithuanian-company-data',
  'patent-search',
  'portuguese-company-data',
  'price-compare',
  'pricing-page-extract',
  'privacy-policy-analyze',
  'product-reviews-extract',
  'product-search',
  'return-policy-extract',
  'salary-benchmark',
  'screenshot-url',
  'seo-audit',
  'singapore-company-data',
  'spanish-company-data',
  'structured-scrape',
  'swedish-company-data',
  'swiss-company-data',
  'tech-stack-detect',
  'terms-of-service-extract',
  'trustpilot-score',
  'url-to-markdown'
);

-- ai_assisted: uses Claude/LLM for processing
UPDATE capabilities SET capability_type = 'ai_assisted' WHERE slug IN (
  'address-parse',
  'agent-trace-analyze',
  'annual-report-extract',
  'api-docs-generate',
  'api-mock-response',
  'blog-post-outline',
  'brand-mention-search',
  'brazilian-company-data',
  'changelog-generate',
  'classify-text',
  'code-convert',
  'code-review',
  'commit-message-generate',
  'company-enrich',
  'context-window-optimize',
  'contract-extract',
  'crontab-generate',
  'curl-to-code',
  'danish-company-data',
  'dockerfile-generate',
  'docstring-generate',
  'email-draft',
  'env-template-generate',
  'error-explain',
  'estonian-company-data',
  'fake-data-generate',
  'finnish-company-data',
  'french-company-data',
  'github-actions-generate',
  'github-repo-analyze',
  'hs-code-lookup',
  'image-to-text',
  'invoice-extract',
  'job-posting-analyze',
  'jsdoc-generate',
  'meeting-notes-extract',
  'nginx-config-generate',
  'norwegian-company-data',
  'openapi-generate',
  'pdf-extract',
  'pii-redact',
  'polish-company-data',
  'pr-description-generate',
  'prompt-compress',
  'prompt-optimize',
  'readme-generate',
  'receipt-categorize',
  'regex-explain',
  'regex-generate',
  'release-notes-generate',
  'resume-parse',
  'sanctions-check',
  'schema-migration-generate',
  'secret-scan',
  'sentiment-analyze',
  'social-post-generate',
  'sql-explain',
  'sql-generate',
  'sql-optimize',
  'summarize',
  'test-case-generate',
  'token-count',
  'translate',
  'uk-company-data',
  'us-company-data',
  'web-extract',
  'webhook-test-payload',
  'youtube-summarize'
);

-- stable_api: external API calls (everything not yet classified stays as default 'stable_api')
-- Explicit list for documentation:
-- api-health-check, backlink-check, barcode-lookup, base64-encode-url, charity-lookup-uk,
-- country-trade-data, crypto-price, currency-convert, cve-lookup, dependency-audit,
-- dns-lookup, docker-hub-info, domain-reputation, ecb-interest-rates, email-deliverability-check,
-- email-validate, eori-validate, exchange-rate, flight-status, food-safety-rating-uk,
-- forex-history, gdpr-website-check, github-repo-compare, github-user-profile, google-search,
-- header-security-check, image-resize, ip-geolocation, job-board-search, keyword-suggest,
-- lei-lookup, link-extract, linkedin-url-validate, meta-extract, mx-lookup, npm-package-info,
-- og-image-check, page-speed-test, port-check, port-lookup, public-holiday-lookup,
-- pypi-package-info, redirect-trace, robots-txt-parse, serp-analyze, sitemap-parse,
-- social-profile-check, ssl-certificate-chain, ssl-check, startup-domain-check, stock-quote,
-- ted-procurement, ticker-lookup, uk-companies-house-officers, uptime-check, url-health-check,
-- url-to-text, vat-validate, weather-lookup, website-carbon-estimate, whois-lookup

-- 3. Add index on capability_type for filtering
CREATE INDEX capabilities_capability_type_idx ON capabilities (capability_type);
