// Human specimens and channel compositions share registry copy and icon geometry.
export const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function templates(r, logo, inverseLogo) {
  const s=r.story;
  const icon=(id,size='medium')=>{const x=r.icons.items.find(x=>x.id===id);if(!x)throw Error(`Unknown icon ${id}`);return `<svg class="utility icon-${size}" viewBox="${r.icons.view_box.join(' ')}" fill="none" stroke="currentColor" stroke-width="${r.icons.stroke_width}" stroke-linecap="${r.icons.linecap}" stroke-linejoin="${r.icons.linejoin}" aria-hidden="true" focusable="false"><path d="${x.path}"/></svg>`;};
  const action=(label,href='#study-detail',kind='primary')=>`<a class="btn ${kind}" href="${href}">${esc(label)}${icon('arrow-right')}</a>`;
  const result=(compact=false)=>`<article class="extraction ${compact?'compact':''}"><span class="label">${esc(s.fixture_label)}</span><h3>Useful fields</h3><dl>${s.result.map(x=>`<div><dt>${esc(x.label)}</dt><dd>${esc(x.value)}</dd></div>`).join('')}</dl></article>`;
  const document=()=>`<article class="paper-document"><div class="row">${icon('document')}<span class="label">${esc(s.document.title)}</span></div><h3>${esc(s.document.company)}</h3><p class="small muted">${esc(s.document.number)}</p><div class="document-lines" aria-hidden="true"><i></i><i></i><i></i></div><div class="document-total"><span>Total</span><strong>${esc(s.document.total)}</strong></div></article>`;
  const art=()=>`<div class="document-stage">${document()}<div class="direction" aria-hidden="true">${icon('arrow-right','large')}</div>${result()}</div>`;
  const website=`<div class="web-study"><header class="study-nav">${logo}<a class="btn text" href="#study-detail">Explore the example</a></header><section class="web-hero" data-density="hero"><div class="hero-copy"><h1>${esc(s.headline)}</h1><p data-body>${esc(s.lead)}</p><div class="row">${action(s.primary,'#study-tools')}${action(s.secondary,'#study-detail','text')}</div></div>${art()}</section><section class="web-editorial" id="study-detail" data-density="section"><div><span class="label">DOCUMENT WORK</span><h2>${esc(s.section_title)}</h2></div><div><p data-body>${esc(s.section_body)}</p><p class="small muted separated">${esc(s.fixture_label)}. This composition shows a concept, not a captured tool response.</p></div></section><section class="web-closing dark" id="study-tools" data-density="card"><h2>${esc(s.closing_title)}</h2><p data-body>${esc(s.closing_body)}</p>${action('Explore tool documentation','#study-destination','inverse')}</section><footer id="study-destination" tabindex="-1" class="study-end"><p class="small muted">Composition study. Tool destinations and the executable example will be verified during website implementation.</p><a class="btn text" href="index.html#website">Back to the guide</a></footer></div>`;
  const social=`<article class="social-art dark" data-density="social"><div class="social-top">${inverseLogo}<span class="label">TOOLS FOR AI AGENTS</span></div><div class="social-main"><div><h1>${esc(s.headline)}</h1><p data-body>${esc(s.lead)}</p></div>${result(true)}</div><div class="social-bottom"><span>strale.dev</span><span>${esc(s.fixture_label)}</span></div></article>`;
  const email=`<article class="email-letter"><header>${logo}</header><h1 data-density-headline="email">${esc(s.headline)}</h1><p>${esc(s.email_body)}</p>${result(true)}<a class="btn primary" href="#email-destination">${esc(s.primary)}</a><p class="email-signoff">Strale</p></article><div class="email-notes" id="email-destination"><p class="small muted">Email composition study. This local destination stands in for a verified catalogue link. Before sending: confirm recipient context, client rendering, destination and required footer.</p><a class="btn text" href="index.html#email">Back to the guide</a></div>`;
  const form=`<form id="preferences" class="form-demo" novalidate><h2>Example preferences</h2><p class="small muted">Local form specimen. Nothing is stored or sent.</p><div class="field"><label for="view-name">View name</label><input id="view-name" name="view-name" required maxlength="60" autocomplete="off" aria-describedby="name-help name-error"><span id="name-help" class="hint">Give this example a name.</span><span id="name-error" class="field-error" hidden>Enter a view name.</span></div><div class="field"><label for="view-note">Description <span class="muted">(optional)</span></label><textarea id="view-note" name="view-note" maxlength="160" rows="2"></textarea></div><div class="field"><label for="view-category">Category</label><select id="view-category" name="view-category"><option>All examples</option><option>Research</option><option>Extraction</option><option>Validation</option></select></div><fieldset><legend>Reading density</legend><div class="choice-row"><label class="choice"><input type="radio" name="density" value="comfortable" checked> Comfortable</label><label class="choice"><input type="radio" name="density" value="compact"> Compact</label></div></fieldset><label class="choice"><input type="checkbox" id="captions" name="captions" checked> Show example captions</label><button class="btn primary" id="save-example" type="submit">Save example</button><p id="save-status" role="status" class="small"></p></form>`;
  const miniField=(label,attributes='',hint='')=>`<div class="field"><label for="state-${label}">${esc(label)}</label><input id="state-${label}" value="Research view" ${attributes}>${hint?`<span class="hint">${esc(hint)}</span>`:''}</div>`;
  const contents={
    forms:`<div class="two form-layout">${form}<aside class="form-notes"><span class="label">START WITH THE TASK</span><h2>Every field earns its place.</h2><p>Labels stay visible. Optional information is marked. The action remains available so people can discover and repair errors.</p><div class="rule"><h3>Try the full path</h3><p class="small muted separated">Submit without a name, correct it, then save. Tab through the select, radios and checkbox.</p><label class="choice separated"><input type="checkbox" id="simulate-failure"> Simulate a save failure</label><p class="small muted">This switch is a testing control, outside the form.</p></div></aside></div>`,
    states:`<div class="two">${miniField('Default')}${miniField('Focus','data-preview-focus','A visible outline follows the keyboard.')}${miniField('Read-only','readonly','Can still be focused and copied.')}${miniField('Unavailable','disabled','Explain what makes this available.')}</div><div class="two rule"><div class="notice error"><div class="row">${icon('alert')}<h3>Couldn’t save this example.</h3></div><p class="small separated">Try again. Your entries are still here.</p><a href="#forms" class="btn text">Try the recovery example</a></div><div class="notice"><div class="row">${icon('check')}<h3>Example ready.</h3></div><p class="small separated">Use a short, accurate confirmation. The interactive specimen makes clear that this is a simulation.</p></div></div><div class="empty-demo rule"><div><h3>No matching examples.</h3><p class="small muted separated">Try a broader search or clear the filters.</p></div><button class="btn secondary" id="clear-example">Clear filters</button><p id="clear-status" role="status" class="small"></p></div><p class="rule small muted">Loading keeps the action’s width and label. No spinner is required. Reduced motion removes colour transitions; status text still announces the outcome.</p>`,
    icons:`<div class="icon-grid">${r.icons.items.map(x=>`<div class="icon-cell"><div class="icon-sizes">${icon(x.id,'small')}${icon(x.id)}${icon(x.id,'large')}</div><span>${esc(x.label)}</span></div>`).join('')}</div><div class="two rule"><div><h3>16 / 20 / 24</h3><p class="small muted separated">Read at actual size. Use the medium size beside controls, and the small size for compact metadata.</p></div><div class="dark icon-inverse"><div class="row">${icon('search')}${icon('document')}${icon('check')}${icon('arrow-right')}</div><p class="small separated">The same outlines inherit light text on dark fields.</p></div></div><p class="rule small muted">Prefer a visible action label. Icon-only controls need an accessible name and a minimum 44px target. Utility symbols never stand in for the Strale logo or become a decoration on every benefit.</p>`,
    density:`<div class="two"><div class="density-example"><span class="label">ONE MESSAGE</span><h2>Make the next step easier.</h2><p class="muted separated">A short explanation, one useful visual and a clear destination for the detail.</p><a class="btn text separated" href="#rhythm">See the composition rules</a></div><div class="budget-list">${r.density.profiles.filter(x=>['hero','section','card','result'].includes(x.id)).map(x=>`<div><strong>${esc(x.label)}</strong><span>${x.headline_words} headline words / ${x.body_words} body words${x.rows_max?` / ${x.rows_max} result rows`:''}</span></div>`).join('')}</div></div><div class="three rule"><div><span class="big-rule">1</span><h3>Primary action</h3><p class="small muted separated">Per decision group. Supporting links remain quieter.</p></div><div><span class="big-rule">1</span><h3>Reading panel</h3><p class="small muted separated">Inside an atmospheric frame. Never another panel inside it.</p></div><div><span class="big-rule">0</span><h3>Automatic subtitles</h3><p class="small muted separated">Add one only when it supplies a distinct fact the reader needs.</p></div></div><p class="rule small muted">These are authoring defaults, not a reason to hide essential instructions. If content exceeds a budget, edit or move detail to a named destination. Document and review any necessary exception at a narrow width.</p>`,
    rhythm:`<div class="rhythm-list"><div><span class="label">01 / OPENING</span><div class="rhythm-split"><h2>Promise beside proof.</h2><div class="rhythm-material dark"><span>A single visual field</span></div></div></div><div><span class="label">02 / EXPLANATION</span><div class="rhythm-open"><h2>Let the page breathe.</h2><p class="muted">An open reading layout explains one benefit without another grid of boxes.</p></div></div><div><span class="label">03 / INVITATION</span><div class="dark rhythm-close"><h2>Make the next step clear.</h2><span class="btn inverse" aria-hidden="true">One action</span></div></div></div><p class="rule small muted">Change alignment, scale and information type when the story changes. Use a card grid for comparable choices. Avoid more than two adjacent sections with the same layout, and keep one decorative field per section.</p>`,
    website:`<div class="application-preview web-preview"><div class="mini-hero"><div><h2>${esc(s.headline)}</h2><p class="small muted separated">${esc(s.lead)}</p>${action(s.primary,'website.html')}</div><div class="dark">${result(true)}</div></div><div class="mini-editorial"><h3>${esc(s.section_title)}</h3><p class="small muted">${esc(s.section_body)}</p></div><div class="dark mini-closing"><h3>${esc(s.closing_title)}</h3>${action(s.primary,'website.html','inverse')}</div></div><div class="row rule">${action('Open website sequence','website.html','secondary')}<p class="small muted">Review the full composition at desktop and mobile widths. The document is an illustrative fixture.</p></div>`,
    social:`<figure class="social-preview"><img src="exports/social-landscape.png" alt="${esc(s.social_alt)}"></figure><div class="two rule"><div><h3>Artwork budget</h3><p class="small muted separated">One headline, one supporting sentence, one evidence object. No pretend button inside a static image.</p></div><div><h3>Caption and alternative text</h3><p class="small muted separated">The accompanying text supplies context beyond the artwork. Alternative text describes both the message and the example.</p></div></div><div class="row separated">${action('Open social study','social.html','secondary')}</div>`,
    email:`<div class="two"><div class="email-mini">${logo}<h2>${esc(s.headline)}</h2><p>${esc(s.email_body)}</p><a class="btn primary" href="email.html">${esc(s.primary)}</a><p>Strale</p></div><div class="stack"><div><span class="label">EMAIL ROLE</span><h2 class="separated">Clarity survives the fallback.</h2><p class="muted separated">Arial carries the body. The retained logo and a compact result example supply recognition without a large decorative background.</p></div><p class="small muted">Subject: ${esc(s.email_subject)}</p><p class="small muted">One primary destination. A plain-text companion. This is a browser composition study; it still needs real mail-client and sending-context checks.</p>${action('Open email study','email.html','secondary')}</div></div>`
  };
  return {contents,website,social,email,icon};
}
