/**
 * Phase B.1 (DEC-20260512-A): 180 capabilities classified as
 * `free_unlimited` from the Phase B.0 audit (2026-05-12) at high
 * confidence. Block 0071 in `startup-migrations.ts` uses this list to
 * bulk-classify the DB rows.
 *
 * **Why this list lives separately.** Same rationale as
 * `llm-capability-costs.ts` and its Block 0064/0065 slug lists: a
 * single-file UPDATE binding 180 inline string literals would be a
 * 200-line SQL template fragment. Keeping the list in its own module
 * makes the diff reviewable and lets `phase-b1-free-unlimited-slugs.test.ts`
 * pin its size + content against the audit CSV.
 *
 * **Source.** `c:/tmp/phase-b-audit-report.csv` (filter:
 * `proposed_cost_class=free_unlimited AND confidence=high`).
 * Regenerable via `c:/tmp/phase-b1-edit-manifests.py` against any
 * future audit run.
 *
 * **Semantics.** These capabilities have one of:
 *   - data_source_type = "computed" (pure-algorithmic, no external API)
 *   - data_source_type = "api" with `maintenance_class =
 *     "free-stable-api"` and no auth env var (gov registry / OpenStreetMap
 *     Nominatim-class endpoints)
 *   - data_source_type = "scrape" without `BROWSERLESS_*` env var (raw
 *     HTTP + cheerio — no vendor cost)
 *
 * **Cost-class semantics.** `free_unlimited` × any invocation context
 * = allow (per ALLOW_MATRIX in `apps/api/src/capabilities/guarded-executor.ts`).
 * Scheduler-eligibility derivation (Block 0069) sets
 * `scheduled_testing_eligible = TRUE` because `free_unlimited IN
 * ('free_unlimited', 'free_quota', 'paid_with_free_tier')`.
 */
export const PHASE_B1_FREE_UNLIMITED_SLUGS: ReadonlyArray<string> = [
  "accessibility-audit",
  "address-geocode",
  "address-validate",
  "age-verify",
  "aml-risk-score",
  "api-health-check",
  "approval-security-check",
  "bank-bic-lookup",
  "barcode-lookup",
  "base64-encode-url",
  "bitcoin-address-validate",
  "brazilian-company-data",
  "business-day-check",
  "c2pa-inspect",
  "charity-lookup-uk",
  "company-id-detect",
  "company-name-match",
  "company-news",
  "contract-verify-check",
  "country-tax-rates",
  "country-trade-data",
  "credit-score-band",
  "cron-explain",
  "crypto-price",
  "csv-clean",
  "csv-to-json",
  "currency-convert",
  "cve-lookup",
  "cz-bank-account-validate",
  "cz-birth-number-validate",
  "cz-datova-schranka-id-validate",
  "cz-ico-validate",
  "cz-unreliable-vat-payer",
  "dangerous-goods-classify",
  "data-protection-authority-lookup",
  "data-quality-check",
  "date-parse",
  "deduplicate",
  "dependency-audit",
  "diff-json",
  "dns-lookup",
  "docker-hub-info",
  "dogecoin-address-validate",
  "domain-age-check",
  "domain-reputation",
  "email-deliverability-check",
  "email-pattern-discover",
  "email-reputation-score",
  "email-validate",
  "employment-cost-estimate",
  "ens-resolve",
  "ens-reverse-lookup",
  "eori-validate",
  "eth-address-validate",
  "eu-ai-act-classify",
  "exchange-rate",
  "fear-greed-index",
  "financial-year-dates",
  "flatten-json",
  "food-safety-rating-uk",
  "forex-history",
  "fr-bodacc-lookup",
  "gas-price-check",
  "gdpr-website-check",
  "gitignore-generate",
  "gleif-l2-children-lookup",
  "gleif-l2-ubo-lookup",
  "header-security-check",
  "holiday-calendar",
  "html-to-pdf",
  "http-to-curl",
  "iban-to-bank",
  "iban-validate",
  "id-number-validate",
  "image-resize",
  "incoterms-explain",
  "invoice-validate",
  "ip-geolocation",
  "ip-risk-score",
  "irish-company-data",
  "isbn-validate",
  "iso-country-lookup",
  "json-repair",
  "json-schema-validate",
  "json-to-csv",
  "json-to-pydantic",
  "json-to-typescript",
  "json-to-zod",
  "jwt-decode",
  "keyword-suggest",
  "language-detect",
  "latvian-company-data",
  "lei-lookup",
  "license-compatibility-check",
  "link-extract",
  "lithuanian-company-data",
  "llm-cost-calculate",
  "llm-output-validate",
  "log-parse",
  "markdown-to-html",
  "marketplace-fee-calculate",
  "meta-extract",
  "mx-lookup",
  "name-parse",
  "nl-housing-price-index",
  "nl-housing-stats",
  "nl-woz-value",
  "no-bankruptcy-check",
  "npm-package-info",
  "og-image-check",
  "openapi-validate",
  "package-security-audit",
  "paid-api-preflight",
  "password-strength",
  "payment-reference-generate",
  "phishing-site-check",
  "phone-normalize",
  "phone-type-detect",
  "phone-validate",
  "port-check",
  "port-lookup",
  "postal-code-lookup",
  "protocol-fees-lookup",
  "protocol-tvl-lookup",
  "public-holiday-lookup",
  "pypi-package-info",
  "redirect-trace",
  "robots-txt-parse",
  "schema-infer",
  "screenshot-url",
  "sec-filing-events",
  "secret-scan",
  "sepa-xml-validate",
  "shipping-cost-estimate",
  "shipping-track",
  "singapore-company-data",
  "sitemap-parse",
  "skill-extract",
  "skill-gap-analyze",
  "slovenian-company-data",
  "social-profile-check",
  "solana-address-validate",
  "ssl-certificate-chain",
  "ssl-check",
  "stablecoin-flow-check",
  "startup-domain-check",
  "stock-quote",
  "swift-message-parse",
  "swift-validate",
  "swiss-company-data",
  "tax-id-validate",
  "ted-procurement",
  "ticker-lookup",
  "timezone-lookup",
  "timezone-meeting-find",
  "token-count",
  "token-security-check",
  "tool-call-validate",
  "tron-address-validate",
  "unit-convert",
  "uptime-check",
  "url-health-check",
  "url-to-markdown",
  "url-to-text",
  "vasp-non-compliant-check",
  "vasp-verify",
  "vat-format-validate",
  "vat-rate-lookup",
  "vat-validate",
  "wallet-age-check",
  "wallet-balance-lookup",
  "wallet-risk-score",
  "wallet-transactions-lookup",
  "weather-lookup",
  "website-carbon-estimate",
  "whois-lookup",
  "work-permit-requirements",
  "workflow-security-audit",
  "xml-to-json",
  "xrp-address-validate",
];
