import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)), root=resolve(here,'../../../..');
const lf=s=>s.replace(/\r\n/g,'\n'), hash=b=>createHash('sha256').update(b).digest('hex');
const read=async p=>lf(await readFile(resolve(root,p),'utf8'));
const registry=JSON.parse(await read('design/brand-kit/quiet-material/hero-comparison/registry.json'));
const tokens=JSON.parse(await read(registry.tokens));
if(registry.status!=='controlled-comparison'||registry.production_adopted||tokens.status!=='proposed') throw Error('Comparison scope changed');
const atmosphere=JSON.parse(await read('design/brand-kit/quiet-material/registry.json'));
if(tokens.palette['--atmosphere-spectrum']!==atmosphere.gradients.find(x=>x.id==='spectrum')?.css)throw Error('Retained Spectrum changed');
const hero=registry.source_bindings.find(x=>x.path.endsWith('/hero-comparison/assets/hero-folded-light.png'));
if(!hero||hero.sha256!==atmosphere.assets.find(x=>x.id==='hero-folded-light-background')?.sha256)throw Error('Retained opening atmosphere changed');
for(const b of registry.source_bindings){let bytes=await readFile(resolve(root,b.path));if(b.mode==='text-lf')bytes=Buffer.from(lf(bytes.toString('utf8')));if(hash(bytes)!==b.sha256)throw Error(`Reference changed: ${b.path}`);}
const css=`:root {\n${Object.entries({...tokens.palette,...tokens.layout.css_variables}).map(([k,v])=>`  ${k}: ${v};`).join('\n')}\n}\n`;
const navigation=['Tools','Use cases','Developers','Pricing','Docs'];
const link=label=>`<a href="index.html#scope">${label}</a>`;
const page=variant=>`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Strale hero — controlled surface comparison</title><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="style.css"><script src="interactions.js" defer></script></head>
<body class="hero-page" data-treatment="${variant}">
<header class="site-header"><a class="logo" href="index.html" aria-label="Return to comparison"><img src="../foundations/exports/lockup-ink.svg" width="176" height="52" alt="Strale"></a><nav class="desktop-nav" aria-label="Primary">${navigation.map(link).join('')}</nav><div class="account">${link('Sign in')}<a class="button primary" href="index.html#scope">Start building <span aria-hidden="true">→</span></a></div><details class="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile">${navigation.map(link).join('')}${link('Sign in')}${link('Start building')}</nav></details></header>
<main><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">Tools for AI agents</p><h1 id="hero-title">One connection to the tools your agent needs.</h1><p class="lead">Search the web, research companies, enrich leads, validate data, run compliance checks and more, without integrating every provider separately.</p><p class="protocol">Connect through <strong>MCP</strong> or <strong>API</strong>, or let your agent pay per request with <strong>x402.</strong></p><div class="actions"><a class="button primary" href="index.html#scope">Explore tools <span aria-hidden="true">→</span></a><a class="button secondary" href="index.html#scope">Start building</a></div><p class="commercial"><span>Pay per call</span><span>Structured results</span><span>Clear pricing</span><span>Charged on success</span></p></div>
<div class="stage"><article class="reading-panel" aria-label="Illustrative email validation example"><header class="request-header"><strong>Strale request</strong><span class="example-label">Illustrative example</span></header><div class="request"><span class="meta">Your agent asks</span><p>Validate these email addresses.</p></div><div class="route"><span>Tool</span><code>email-validate</code></div><dl class="results"><div><dt>Format</dt><dd>Valid</dd></div><div><dt>MX records</dt><dd>Found</dd></div><div><dt>Disposable</dt><dd>No</dd></div></dl><footer class="request-footer">One request · structured result · source context</footer></article></div></section></main></body></html>\n`;
const index=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Strale — original hero surface comparison</title><link rel="stylesheet" href="tokens.css"><link rel="stylesheet" href="style.css"><script src="interactions.js" defer></script></head><body class="review"><header><h1>The original hero, with a lighter inner treatment.</h1><p>Same atmosphere, scale, wording and example. Only frame inset, reading surface and its padding change.</p><p><a href="../baseline/evidence/founder-hero.png">Exact original screenshot</a> · <a href="README.md">Scope and source notes</a></p></header><main><figure class="reference"><figcaption>Controlling reference · exact supplied screenshot</figcaption><a href="../baseline/evidence/founder-hero.png"><img src="../baseline/evidence/founder-hero.png" alt="Exact founder-supplied original design, retained as the controlling reference."></a></figure><div class="comparison"><section><h2>A · Reconstructed control</h2><p>Screenshot-guided reconstruction.</p><a href="control.html"><img src="output/control-desktop.png" alt="Original-treatment hero reconstruction. Open at full size."></a><p><a href="control.html">Open full-size A</a></p></section><section><h2>B · Refined reading surface</h2><p>Substantial colour frame, clearer paper surface.</p><a href="refined.html"><img src="output/refined-desktop.png" alt="Refined hero preserving the original composition. Open at full size."></a><p><a href="refined.html">Open full-size B</a></p></section></div><h2>Narrow layouts</h2><p>Both are study interpretations; an exact original mobile revision was not supplied.</p><div class="comparison narrow"><section><h3>A · Reconstructed control</h3><img src="output/control-mobile.png" alt="Original treatment at 390 pixels."></section><section><h3>B · Refined reading surface</h3><img src="output/refined-mobile.png" alt="Refined treatment at 390 pixels."></section></div><section id="scope"><h2>What to assess</h2><p>Does B retain the original character while making the inner panel feel better balanced and easier to read?</p><p>Both examples are illustrative. The historical wording is held only to isolate this visual change; it is not approved launch copy. Links return here because this is a local design comparison, not the live website. A is a reconstruction, not recovered source for the exact screenshot.</p></section></main></body></html>\n`;
const output={'style.css':(await read('design/brand-kit/quiet-material/hero-comparison/style.template.css')).replaceAll('__BREAKPOINT__',String(tokens.layout.breakpoint_px)),'tokens.css':css,'control.html':page('control'),'refined.html':page('refined'),'index.html':index};
const inputs={};for(const path of ['registry.json','style.template.css','build.mjs','interactions.js'])inputs[path]=hash(await read(`design/brand-kit/quiet-material/hero-comparison/${path}`));inputs[registry.tokens]=hash(await read(registry.tokens));
output['manifest.json']=JSON.stringify({inputs,outputs:Object.fromEntries(Object.entries(output).map(([k,v])=>[k,hash(v)]))},null,2)+'\n';
for(const [file,content]of Object.entries(output)){const path=resolve(here,file);if(process.argv.includes('--check')){if(lf(await readFile(path,'utf8'))!==content)throw Error(`Stale output: ${file}`);}else await writeFile(path,content,'utf8');}
if(process.argv.includes('--check')){
 const evidence=JSON.parse(await readFile(resolve(here,'verification.json'),'utf8'));
 const checks=['same_content_and_outer_geometry','only_panel_treatment_changes','responsive_bounds','local_assets_and_fonts','refined_reading_text_contrast','keyboard_menu','local_destinations','no_remote_requests','no_browser_errors'];
 const screenshots=['output/control-desktop.png','output/control-mobile.png','output/refined-desktop.png','output/refined-mobile.png'];
 if(evidence.status!=='passed'||evidence.manifest_sha256!==hash(output['manifest.json'])||evidence.verifier_sha256!==hash(lf(await readFile(resolve(here,'verify.mjs'),'utf8'))))throw Error('Stale browser evidence');
 if(JSON.stringify(evidence.widths)!==JSON.stringify([320,390,900,1100,1101,1120,1440])||JSON.stringify(Object.keys(evidence.checks).sort())!==JSON.stringify(checks.sort())||Object.values(evidence.checks).some(v=>v!==true))throw Error('Incomplete browser checks');
 if(JSON.stringify(Object.keys(evidence.screenshots).sort())!==JSON.stringify(screenshots.sort()))throw Error('Incomplete screenshot evidence');
 for(const file of screenshots)if(hash(await readFile(resolve(here,file)))!==evidence.screenshots[file])throw Error(`Stale screenshot: ${file}`);
}
console.log('Hero comparison sources and generated outputs agree.');
