import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
export const here=dirname(fileURLToPath(import.meta.url)),repo=resolve(here,'../../../..');
const read=p=>readFileSync(resolve(here,p),'utf8');
export const json=p=>JSON.parse(read(p));
export const digest=p=>createHash('sha256').update(readFileSync(resolve(here,p))).digest('hex');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageIds=['overview','buttons','navigation','mobile','cards','feedback'];
export const inputs=['registry.json','build.mjs','specimen.css','interactions.js','verify.mjs','verify-pdf.py','../../../tokens/candidates/quiet-material-controls.json','../../../tokens/candidates/quiet-material-foundations.json','../foundations/registry.json','../foundations/exports/lockup-ink.svg','../fonts/InstrumentSans.ttf','../fonts/IBMPlexMono-Regular.ttf'];
export function inputHashes(){return Object.fromEntries(inputs.map(p=>[p,digest(p)]));}
export function validate(r,t) {
  assert.equal(r.id,'quiet-material-controls-0.1');assert.equal(r.status,'candidate');assert.equal(r.production_adopted,false);
  assert.equal(t.status,'proposed');assert.deepEqual(r.pages,pageIds);assert.deepEqual(r.rules.map(x=>x.id),pageIds);
  assert.deepEqual(r.buttons,{variants:['primary','secondary','text','inverse'],states:['default','hover','active','focus-visible','disabled','loading'],min_target_px:44,primary_per_group:1});
  assert.deepEqual(r.navigation,{pattern:'disclosure',escape:'close-and-return-focus',outside:'close',focus_leaves:'close',secondary:'native-anchor-navigation',mobile:'inline-disclosure-not-modal'});
  assert.deepEqual(r.cards.patterns,['marketing','discovery','result']);assert.equal(r.cards.max_nested_reading_panels,1);
  assert.deepEqual(r.cards.marketing,{headings:1,paragraphs_max:1,primary_actions_max:1});
  assert.deepEqual(r.cards.discovery,{headings:1,paragraphs_max:1,metadata_rows_max:1,interactive_model:'single-anchor'});assert.deepEqual(r.cards.result,{interactive_model:'contained-actions',fixture_rows:3,fixture_only:true});
  assert.equal(r.limits.length,5);assert(r.limits.every(x=>typeof x==='string'&&x.length>20));
  const base=json('../../../tokens/candidates/quiet-material-foundations.json');
  assert.deepEqual(t.type,base.type,'Type roles drifted');assert.deepEqual(t.layout.identity,base.layout.identity,'Identity geometry drifted');for(const radius of base.radii)assert(t.radii.includes(radius),'Retained radius missing');for(const space of base.spacing)assert(t.spacing.includes(space),'Retained spacing missing');
  for(const [key,value] of Object.entries(base.layout.css_variables))assert.equal(t.layout.css_variables[key],value,`Retained token changed: ${key}`);
  for(const [key,value] of Object.entries(t.palette))assert.equal(t.layout.css_variables[key],value,'Palette drift');
  assert.equal(t.layout.css_variables['--control-compact'],r.buttons.min_target_px+'px');
  assert.equal(t.layout.page_count,pageIds.length);
  const css=read('specimen.css');
  assert(!/#[0-9a-f]{3,8}\b|\b\d+(?:\.\d+)?(?:px|pt|rem|em|ms)\b/i.test(css),'Off-token CSS');
  for(const match of css.matchAll(/var\((--[\w-]+)/g))assert(match[1] in t.layout.css_variables,`Unknown token ${match[1]}`);
  const fonts=json('../foundations/registry.json').fonts.filter(x=>x.role==='font');
  for(const font of fonts)assert.equal(digest('../'+font.file.replace(/^\.\.\//,'')),font.sha256,'Font changed');
  return true;
}
export function render(r,t) {
  validate(r,t);
  const uri=(p,mime)=>`data:${mime};base64,${readFileSync(resolve(here,p)).toString('base64')}`;
  const logo=`<img class="logo" src="${uri('../foundations/exports/lockup-ink.svg','image/svg+xml')}" alt="Strale">`;
  const arrow='<span class="arrow" aria-hidden="true">→</span>';
  const link=(label,kind='primary',extra='')=>`<a href="#specimen-status" class="btn ${kind}" data-demo-link="${escape(label)}" ${extra}>${escape(label)}${kind==='primary'?arrow:''}</a>`;
  const navLink=label=>`<a class="nav-link" href="#specimen-status" data-demo-link="${escape(label)}">${escape(label)}</a>`;
  const mobileLinks=`<ul class="mobile-links">${['Tools','Use cases','Developers','Pricing','Docs','Sign in'].map(s=>`<li>${navLink(s)}</li>`).join('')}</ul>${link('Start building')}`;
  const rule=id=>`<p class="rule small muted">${escape(r.rules.find(x=>x.id===id).guidance)}</p>`;
  const contents={
    overview:`<div class="two"><div class="dark" data-pattern="marketing"><span class="label">SHORT MARKETING MESSAGE</span><h2 class="separated">Start with one useful task.</h2><p>Find a tool that fits the work.</p><div class="row">${link('Explore tools','inverse')}</div></div><div class="stack"><div><h2>Quiet by default.</h2><p class="separated muted">A strong primary action. An open reading surface. Detail only where it helps someone decide.</p></div><div class="row">${link('Explore tools')}${link('Read the docs','text')}</div></div></div><div class="three rule"><div><span class="label">01 / NAVIGATE</span><p class="separated">Keep familiar labels and a visible current location.</p></div><div><span class="label">02 / ACT</span><p class="separated">Give every action a clear priority and a complete set of states.</p></div><div><span class="label">03 / READ</span><p class="separated">Use direct text for an invitation; a reading panel for detail.</p></div></div>`,
    buttons:`<div class="four"><div class="state">${link('Explore tools')}<span class="state-name">Primary / one per group</span></div><div class="state">${link('View examples','secondary')}<span class="state-name">Secondary / supporting action</span></div><div class="state">${link('Read the docs','text')}<span class="state-name">Text / useful next detail</span></div><div class="dark">${link('Start building','inverse')}<p class="small separated">Inverse / on dark fields</p></div></div><div class="four rule"><div class="state"><button class="btn primary" data-state="hover">Explore tools</button><span class="state-name">Hover / brighter ink</span></div><div class="state"><button class="btn primary" data-state="active">Explore tools</button><span class="state-name">Pressed / steady position</span></div><div class="state"><button class="btn primary" data-state="focus">Explore tools</button><span class="state-name">Keyboard / persistent outline</span></div><div class="state"><button class="btn" disabled aria-describedby="unavailable">Continue</button><span id="unavailable" class="state-name">Unavailable / choose a tool first</span></div></div><div class="row rule"><button id="run-example" class="btn primary">Load example</button><p id="example-feedback" class="small muted" role="status">Try loading a local fixture. No API request.</p></div>${rule('buttons')}`,
    navigation:`<nav aria-label="Desktop specimen" class="nav-demo"><div class="nav-bar">${logo}<ul class="nav-links"><li><button id="tools-trigger" class="nav-link" data-disclosure aria-expanded="false" aria-controls="tools-panel">Tools <span class="caret" aria-hidden="true"></span></button><div id="tools-panel" class="disclosure-panel print-open" hidden><ul>${['Browse tools','Research','Extraction','Validation'].map(s=>`<li>${navLink(s)}</li>`).join('')}</ul></div></li>${['Use cases','Developers','Pricing','Docs'].map(s=>`<li>${navLink(s)}</li>`).join('')}</ul><span class="desktop-action row">${navLink('Sign in')}${link('Start building')}</span><button class="nav-link mobile-trigger" id="responsive-trigger" data-disclosure aria-expanded="false" aria-controls="responsive-panel">Menu <span class="caret" aria-hidden="true"></span></button><div id="responsive-panel" class="desktop-mobile-panel mobile-panel" hidden>${mobileLinks}</div></div></nav><div class="nav-space"><p class="small muted print-hidden">Try the navigation with Tab, Enter and Escape.</p></div><h3>Within a topic</h3><nav aria-label="Topic specimen" class="section-nav"><a data-topic href="#overview" aria-current="location">Overview</a><a data-topic href="#cards">Examples</a><a data-topic href="#feedback">States</a></nav>${rule('navigation')}`,
    mobile:`<div class="two"><div class="device"><nav aria-label="Mobile specimen"><div class="mobile-bar">${logo}<button id="mobile-trigger" class="nav-link" data-disclosure aria-expanded="false" aria-controls="mobile-panel">Menu <span class="caret" aria-hidden="true"></span></button></div><div id="mobile-panel" class="mobile-panel print-open" hidden>${mobileLinks}</div></nav><div class="mobile-content print-hidden"><h2>Find a useful tool.</h2><p class="small muted">Open the menu above. The content moves down as the links appear.</p></div></div><div class="stack"><div><span class="label">SAME IDENTITY</span><h2 class="separated">Less space. The same clarity.</h2><p class="separated muted">The logo stays at its tested minimum width. Navigation opens in the page, with readable labels and generous targets.</p></div><div><h3>Behaviour to try</h3><p class="separated small">Open with Enter or Space. Tab through the links. Escape closes the menu and returns to its button. Tabbing out closes it too.</p></div><p class="small muted">At narrow widths, the desktop example above uses this same pattern.</p></div></div>${rule('mobile')}`,
    cards:`<div class="three"><div><div class="dark" data-pattern="marketing"><h2>Put a useful tool to work.</h2><p>Start with a task your agent already needs to do.</p><div class="row">${link('Explore tools','inverse')}</div></div><p class="small muted separated">Marketing / one message and one action.</p></div><div><a class="card" href="#specimen-status" data-demo-link="Email validation" data-pattern="discovery"><span class="label">VALIDATION</span><h3 class="separated">Email validation</h3><p class="muted">Check an address before putting it to work.</p><div class="meta"><span>Tool details</span>${arrow}</div></a><p class="small muted separated">Discovery / the whole card is one link.</p></div><div><div class="frame" style="background:var(--atmosphere-dusk)"><article class="card result" data-pattern="result"><span class="label">ILLUSTRATIVE FIXTURE</span><h3 class="separated">Email check</h3><dl><div><dt>Format</dt><dd class="good">Valid</dd></div><div><dt>MX records</dt><dd>Found</dd></div><div><dt>Disposable</dt><dd>No</dd></div></dl><div class="row">${link('View details','text')}</div></article></div><p class="small muted separated">Result / a light panel for structured detail.</p></div></div>${rule('cards')}`,
    feedback:`<div class="two"><div class="notice"><span class="label">SUCCESS / DESIGN FIXTURE</span><h3 class="separated">Example ready.</h3><p class="separated small">Show a concise outcome and let the person continue.</p></div><div class="notice error"><span class="label">ERROR / DESIGN FIXTURE</span><h3 class="separated">We couldn’t load this example.</h3><p class="separated small">Try again. Your input is still here.</p><button id="retry-example" class="btn secondary">Try again</button><p id="retry-feedback" class="small" role="status"></p></div></div><div class="two rule"><div><h3>Text carries the meaning.</h3><p class="separated muted">Colour reinforces success or error. It never supplies the only explanation. Loading and retry examples announce their outcome.</p></div><div><h3>Motion stays restrained.</h3><p class="separated muted">Only colour changes transition. Controls do not jump or grow. Reduced motion removes the transition.</p></div></div>${rule('feedback')}<p id="specimen-status" class="specimen-status" role="status" tabindex="-1">Local component specimen. Links announce their intended destination here.</p>`
  };
  const pages=r.pages.map((id,i)=>{const row=r.rules[i];return `<section class="sheet" id="${id}"><div class="mast">${logo}<span class="label">QUIET MATERIAL / ${escape(id.toUpperCase())}</span></div><h1>${escape(row.title)}</h1><p class="intro">${escape(row.summary)}</p><div class="body">${contents[id]}</div><div class="footer"><span>COMPONENT CANDIDATE 0.1 / LOCAL DESIGN SPECIMEN</span><span>${String(i+1).padStart(2,'0')}</span></div></section>`;}).join('');
  const v=t.layout.css_variables;
  const css=read('specimen.css').replace('BREAKPOINT',t.layout.responsive_breakpoint_px+'px').replace('PRINT_SIZE',`${v['--page-width']} ${v['--page-height']}`);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Strale navigation, controls and cards</title><style>@font-face{font-family:"Instrument Sans";src:url(${uri('../fonts/InstrumentSans.ttf','font/ttf')});font-weight:400 700;font-style:normal}@font-face{font-family:"IBM Plex Mono";src:url(${uri('../fonts/IBMPlexMono-Regular.ttf','font/ttf')});font-weight:400;font-style:normal}:root{${Object.entries(v).map(([k,x])=>`${k}:${x}`).join(';')}}${css}</style></head><body><main>${pages}</main><script>${read('interactions.js')}</script></body></html>\n`;
}
export function validateEvidence(e,r) {
  assert.equal(e.id,r.id);assert.equal(e.production_adopted,false);assert.deepEqual(e.inputs,inputHashes());
  assert.deepEqual(e.widths,[320,375,760,1120,1440]);assert.deepEqual(e.layout_errors,[]);assert.deepEqual(e.console_errors,[]);
  for(const key of ['desktop_keyboard','outside_close','focus_leaves_close','mobile_keyboard','responsive_menu','hidden_links_unfocusable','loading_guard','retry_announcement','focus_visible','reduced_motion','no_nested_targets','targets_minimum','contrast_pairs','print_bounds','card_contract','open_state_layout'])assert.equal(e.checks[key],true,`Missing check: ${key}`);
  assert(e.runtime.chromium&&e.runtime.node&&e.runtime.playwright);
  assert.deepEqual(e.limits,r.limits);
  assert.equal(e.outputs['index.html'],digest('index.html'));assert.equal(e.outputs['output/pdf/navigation-controls.pdf'],digest('output/pdf/navigation-controls.pdf'));
  assert.equal(e.pdf.pages,6);assert.equal(e.pdf.all_fonts_embedded,true);assert.deepEqual(e.pdf.bounds_errors,[]);
  assert.equal(e.dark_contrast.length,6);assert(e.dark_contrast.every(x=>x.ratio>=4.5&&/^[a-f0-9]{64}$/.test(x.background_sha256)));
}
function main(){const r=json('registry.json'),t=json('../../../tokens/candidates/quiet-material-controls.json');const html=render(r,t);if(process.argv.includes('--check')){assert.equal(read('index.html'),html,'Stale HTML');validateEvidence(json('verification.json'),r);console.log('Controls source, output and evidence bindings pass');}else{mkdirSync(resolve(here,'output/pdf'),{recursive:true});mkdirSync(resolve(here,'.preview'),{recursive:true});writeFileSync(resolve(here,'index.html'),html);console.log('Built standalone controls specimen');}}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main();
